# Encoding: UTF-8

{fileTypes: ["ini", "conf"],
 foldingStartMarker: /\[/,
 foldingStopMarker: /\[/,
 keyEquivalent: "^~I",
 name: "Ini",
 patterns: 
  [{captures: {1 => {name: "punctuation.definition.comment.ini"}},
    match: /(?<_1>#).*$\n?/,
    name: "comment.line.number-sign.ini"},
   {captures: {1 => {name: "punctuation.definition.comment.ini"}},
    match: /(?<_1>;).*$\n?/,
    name: "comment.line.semicolon.ini"},
   {captures: 
     {1 => {name: "keyword.other.definition.ini"},
      2 => {name: "punctuation.separator.key-value.ini"}},
    match: /\b(?<_1>[a-zA-Z0-9_.-]+)\b\s*(?<_2>=)/},
   {captures: 
     {1 => {name: "punctuation.definition.entity.ini"},
      3 => {name: "punctuation.definition.entity.ini"}},
    match: /^(?<_1>\[)(?<_2>.*?)(?<_3>\])/,
    name: "entity.name.section.group-title.ini"},
   {begin: /'/,
    beginCaptures: {0 => {name: "punctuation.definition.string.begin.ini"}},
    end: "'",
    endCaptures: {0 => {name: "punctuation.definition.string.end.ini"}},
    name: "string.quoted.single.ini",
    patterns: [{match: /\\./, name: "constant.character.escape.ini"}]},
   {begin: /"/,
    beginCaptures: {0 => {name: "punctuation.definition.string.begin.ini"}},
    end: "\"",
    endCaptures: {0 => {name: "punctuation.definition.string.end.ini"}},
    name: "string.quoted.double.ini"}],
 scopeName: "source.ini",
 uuid: "77DC23B6-8A90-11D9-BAA4-000A9584EC8C"}
