# Encoding: UTF-8

{fileTypes: ["moinmoin"],
 keyEquivalent: "^~M",
 name: "MoinMoin",
 patterns: 
  [{captures: 
     {1 => {name: "punctuation.definition.heading.moimoin"},
      2 => {name: "punctuation.definition.heading.moimoin"}},
    match: /^\s*(?<_1>=)\s.*\s(?<_2>=)$\n?/,
    name: "markup.heading.1.moinmoin"},
   {captures: 
     {1 => {name: "punctuation.definition.heading.moimoin"},
      2 => {name: "punctuation.definition.heading.moimoin"}},
    match: /^\s*(?<_1>==)\s.*\s(?<_2>==)$\n?/,
    name: "markup.heading.2.moinmoin"},
   {captures: 
     {1 => {name: "punctuation.definition.heading.moimoin"},
      2 => {name: "punctuation.definition.heading.moimoin"}},
    match: /^\s*(?<_1>===)\s.*\s(?<_2>===)$\n?/,
    name: "markup.heading.3.moinmoin"},
   {captures: 
     {1 => {name: "punctuation.definition.heading.moimoin"},
      2 => {name: "punctuation.definition.heading.moimoin"}},
    match: /^\s*(?<_1>====)\s.*\s(?<_2>====)$\n?/,
    name: "markup.heading.4.moinmoin"},
   {captures: 
     {1 => {name: "punctuation.definition.heading.moimoin"},
      2 => {name: "punctuation.definition.heading.moimoin"}},
    match: /^\s*(?<_1>=====)\s.*\s(?<_2>=====)$\n?/,
    name: "markup.heading.5.moinmoin"},
   {match: /^\s*-----\s*$\n?/, name: "meta.separator.moinmoin"},
   {match: /^#pragma.*/, name: "meta.pragma.moimoin"},
   {captures: {1 => {name: "punctuation.definition.comment.moimoin"}},
    match: /^(?<_1>##).*$\n?/,
    name: "comment.line.double-number-sign.moimoin"},
   {begin: /^\s+(?<_1>.*?(?<_2>::))(?=\s+\S)/,
    captures: 
     {1 => {name: "markup.list.definition.term.moinmoin"},
      2 => {name: "punctuation.separator.definition.moinmoin"}},
    contentName: "markup.list.definition.moinmoin",
    end: "\\n",
    patterns: [{include: "#inline"}]},
   {begin: /^\s+(?<_1>\*)(?<_2>\s)/,
    captures: 
     {1 => {name: "punctuation.definition.list_item.moinmoin"},
      2 => {name: "markup.list.unnumbered.moinmoin"}},
    contentName: "markup.list.unnumbered.moinmoin",
    end: "\\n",
    patterns: [{include: "#inline"}]},
   {begin: /^\s+(?<_1>(?:[aAiI]|\d+)\.(?:\#\d+)?)(?<_2>\s)/,
    captures: 
     {1 => {name: "punctuation.definition.list_item.moinmoin"},
      2 => {name: "markup.list.numbered.moinmoin"}},
    contentName: "markup.list.numbered.moinmoin",
    end: "\\n",
    patterns: [{include: "#inline"}]},
   {begin: /^\s*(?<_1>\|\|)/,
    captures: 
     {1 => {name: "punctuation.definition.table.column.moinmoin"},
      2 => {name: "punctuation.definition.table.column.moinmoin"}},
    contentName: "meta.table.moinmoin",
    end: "(\\|\\|$)|\\n",
    patterns: [{include: "#inline"}]},
   {begin: /^\s*(?=\S)/,
    end: "\\n",
    name: "meta.paragraph.moinmoin",
    patterns: [{include: "#inline"}]}],
 repository: 
  {inline: 
    {patterns: 
      [{begin: /\{{3}(?!.*\}{3})/,
        captures: {0 => {name: "punctuation.definition.raw.moinmoin"}},
        end: "\\}{3}",
        name: "markup.raw.block.moinmoin"},
       {captures: 
         {1 => {name: "punctuation.definition.raw.moinmoin"},
          2 => {name: "punctuation.definition.raw.moinmoin"},
          3 => {name: "punctuation.definition.raw.moinmoin"},
          4 => {name: "punctuation.definition.raw.moinmoin"}},
        match: /(?<_1>`)[^`]*(?<_2>`)|(?<_3>{{{).*?(?<_4>}}})/,
        name: "markup.raw.inline.moinmoin"},
       {begin: /'{2}(?='{3}[^']*'{3})/,
        captures: {0 => {name: "punctuation.definition.italic.moinmoin"}},
        contentName: "markup.italic.moinmoin",
        end: "'{2}(?!')|'{2}(?='{3})",
        patterns: [{include: "#inline"}]},
       {begin: /'{3}/,
        captures: {0 => {name: "punctuation.definition.bold.moinmoin"}},
        contentName: "markup.bold.moinmoin",
        end: "'{3}",
        patterns: [{include: "#inline"}]},
       {begin: /'{2}/,
        captures: {0 => {name: "punctuation.definition.italic.moinmoin"}},
        contentName: "markup.italic.moinmoin",
        end: "'{2}(?!')|'{2}(?='{3})",
        patterns: [{include: "#inline"}]},
       {begin: /__/,
        captures: {0 => {name: "punctuation.definition.underline.moinmoin"}},
        contentName: "markup.underline.moinmoin",
        end: "__",
        patterns: [{include: "#inline"}]},
       {match: /(?<!\!)\/?(?:[A-Z][a-z0-9]+[A-Z][a-z0-9]+[A-Za-z0-9]*)/,
        name: "markup.underline.link.moinmoin"},
       {captures: 
         {1 => {name: "punctuation.definition.link.moinmoin"},
          2 => {name: "punctuation.definition.link.moinmoin"}},
        match: /(?<_1>\[").*?(?<_2>"\])/,
        name: "markup.underline.link.moinmoin"},
       {captures: 
         {1 => {name: "punctuation.definition.link.moinmoin"},
          2 => {name: "punctuation.definition.link.moinmoin"}},
        match: /(?<_1>\[):.*?:.*?(?<_2>\])/,
        name: "markup.underline.link.moinmoin"},
       {match: /https?:\/\/\S+/, name: "markup.underline.link.moinmoin"},
       {captures: 
         {1 => {name: "punctuation.definition.link.moinmoin"},
          2 => {name: "punctuation.definition.link.moinmoin"}},
        match: /(?<_1>\[)https?:\/\/.*?(?<_2>\])/,
        name: "markup.underline.link.moinmoin"},
       {captures: {1 => {name: "punctuation.separator.key-value.moinmoin"}},
        match: /attachment(?<_1>:)\S+/,
        name: "markup.underline.link.moinmoin"},
       {captures: 
         {0 => {name: "punctuation.definition.table.column.moinmoin"}},
        match: /\|\|/,
        name: "meta.table.column.moinmoin"},
       {captures: {0 => {name: "punctuation.definition.macro.moinmoin"}},
        match: /(?<_1>\[\[).*?(?<_2>\]\])/,
        name: "meta.macro.moinmoin"}]}},
 scopeName: "text.moinmoin",
 uuid: "DB315CBC-23FD-4952-9D64-F2AC0618A840"}
