# Encoding: UTF-8

{keyEquivalent: "^~T",
 name: "Twiki",
 patterns: 
  [{begin: /"/,
    beginCaptures: {0 => {name: "punctuation.definition.string.begin.twiki"}},
    end: "\"",
    endCaptures: {0 => {name: "punctuation.definition.string.end.twiki"}},
    name: "string.quoted.double.twiki",
    patterns: [{match: /\\./, name: "constant.character.escape.twiki"}]},
   {captures: 
     {1 => {name: "punctuation.definition.heading.twiki"},
      2 => {name: "entity.name.function.twiki"}},
    match: /^(?<_1>-{3}\+{1,6})(?<_2>.*)$/,
    name: "markup.heading.twiki"},
   {begin: /(?<_1><)verbatim(?<_2>>)|(?<_3><)pre(?<_4>>)/,
    captures: 
     {1 => {name: "punctuation.definition.tag.twiki"},
      2 => {name: "punctuation.definition.tag.twiki"},
      3 => {name: "punctuation.definition.tag.twiki"},
      4 => {name: "punctuation.definition.tag.twiki"}},
    end: "(</)verbatim(>)|(</)pre(>)",
    name: "markup.raw.twiki",
    patterns: [{match: /\\./, name: "constant.character.escape.twiki"}]},
   {match: /^-{3,}$\n/, name: "meta.separator.twiki"},
   {begin: /^ {3}(?<_1>[a-zA-Z0-9]+: )/,
    captures: 
     {1 => {name: "markup.other.def.term.twiki"},
      2 => {name: "markup.other.def.def.twiki"}},
    end: "$\\n?",
    name: "markup.other.def.twiki",
    patterns: [{include: "#list-paragraph"}]},
   {begin: /^(?<_1>\|)/,
    beginCaptures: {1 => {name: "punctuation.definition.table.twiki"}},
    end: "^(?:\\s*$|(?=\\s*>|[=-]{3,}$))",
    name: "markup.other.table.twiki",
    patterns: [{include: "#inline"}]},
   {begin: /^ {3}(?<_1>\*)/,
    beginCaptures: {1 => {name: "punctuation.definition.list_item.twiki"}},
    end: "$\\n?",
    name: "markup.list.unnumbered.1.twiki",
    patterns: [{include: "#list-paragraph"}]},
   {begin: /^ {6}(?<_1>\*)/,
    beginCaptures: {1 => {name: "punctuation.definition.list_item.twiki"}},
    end: "$\\n?",
    name: "markup.list.unnumbered.2.twiki",
    patterns: [{include: "#list-paragraph"}]},
   {begin: /^ {9}(?<_1>\*)/,
    beginCaptures: {1 => {name: "punctuation.definition.list_item.twiki"}},
    end: "$\\n?",
    name: "markup.list.unnumbered.3.twiki",
    patterns: [{include: "#list-paragraph"}]},
   {begin: /^ {12}(?<_1>\*)/,
    beginCaptures: {1 => {name: "punctuation.definition.list_item.twiki"}},
    end: "$\\n?",
    name: "markup.list.unnumbered.4.twiki",
    patterns: [{include: "#list-paragraph"}]},
   {begin: /^ {15}(?<_1>\*)/,
    beginCaptures: {1 => {name: "punctuation.definition.list_item.twiki"}},
    end: "$\\n?",
    name: "markup.list.unnumbered.5.twiki",
    patterns: [{include: "#list-paragraph"}]},
   {begin: /^ {18}(?<_1>\*)/,
    beginCaptures: {1 => {name: "punctuation.definition.list_item.twiki"}},
    end: "$\\n?",
    name: "markup.list.unnumbered.6.twiki",
    patterns: [{include: "#list-paragraph"}]},
   {begin: /^ {3}\d/,
    end: "$\\n?",
    name: "markup.list.numbered.1.twiki",
    patterns: [{include: "#numlist-paragraph"}]},
   {begin: /^ {6}\d/,
    end: "$\\n?",
    name: "markup.list.numbered.2.twiki",
    patterns: [{include: "#numlist-paragraph"}]},
   {begin: /^ {9}\d/,
    end: "$\\n?",
    name: "markup.list.numbered.3.twiki",
    patterns: [{include: "#numlist-paragraph"}]},
   {begin: /^ {12}\d/,
    end: "$\\n?",
    name: "markup.list.numbered.4.twiki",
    patterns: [{include: "#numlist-paragraph"}]},
   {begin: /^ {15}\d/,
    end: "$\\n?",
    name: "markup.list.numbered.5.twiki",
    patterns: [{include: "#numlist-paragraph"}]},
   {begin: /^ {18}\d/,
    end: "$\\n?",
    name: "markup.list.numbered.6.twiki",
    patterns: [{include: "#numlist-paragraph"}]},
   {begin: /^(?=\S)/,
    end: "^\\s*$",
    name: "meta.paragraph.twiki",
    patterns: [{include: "#inline"}, {include: "text.html.basic"}]}],
 repository: 
  {inline: 
    {patterns: 
      [{captures: 
         {1 => {name: "punctuation.definition.bold.twiki"},
          2 => {name: "punctuation.definition.bold.twiki"}},
        match: /(?<_1>[\*])[\s\w :.\?']*(?<_2>[\*])/,
        name: "markup.bold.twiki"},
       {captures: 
         {1 => {name: "markup.bold.twiki"},
          2 => {name: "markup.italic.twiki"},
          3 => {name: "punctuation.definition.bold.twiki"},
          4 => {name: "punctuation.definition.italic.twiki"},
          5 => {name: "punctuation.definition.bold.twiki"},
          6 => {name: "punctuation.definition.italic.twiki"}},
        match: /(?<_1>(?<_2>(?<_3>(?<_4>__))[\s\w :.\?']*(?<_5>(?<_6>__))))/},
       {captures: 
         {1 => {name: "punctuation.definition.italic.twiki"},
          2 => {name: "punctuation.definition.italic.twiki"}},
        match: /\b(?<_1>_)[\s\w :.\?']*(?<_2>_)\b/,
        name: "markup.italic.twiki"},
       {captures: 
         {1 => {name: "markup.bold.twiki"},
          2 => {name: "markup.raw.fixed.twiki"},
          3 => {name: "punctuation.definition.bold.twiki"},
          4 => {name: "punctuation.definition.raw.fixed.twiki"},
          5 => {name: "punctuation.definition.bold.twiki"},
          6 => {name: "punctuation.definition.raw.fixed.twiki"}},
        match: 
         /(?<_1>(?<_2>(?<_3>(?<_4>\=\=))[\s\w :.\?']*(?<_5>(?<_6>\=\=))))/},
       {captures: 
         {1 => {name: "punctuation.definition.raw.fixed.twiki"},
          2 => {name: "punctuation.definition.raw.fixed.twiki"}},
        match: /(?<_1>\=)[\s\w :.\?']*(?<_2>\=)/,
        name: "markup.raw.fixed.twiki"},
       {captures: 
         {1 => {name: "punctuation.definition.variable.twiki"},
          3 => {name: "punctuation.definition.variable.twiki"}},
        match: /(?<_1>%)(?<_2>[A-Z0-9]+)(?<_3>%)/,
        name: "variable.other.twiki"},
       {captures: 
         {1 => {name: "punctuation.definition.constant.twiki"},
          3 => {name: "punctuation.definition.constant.twiki"}},
        match: /(?<_1>&)(?<_2>[a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(?<_3>;)/,
        name: "constant.character.entity.html"},
       {captures: 
         {1 => {name: "punctuation.definition.link.twiki"},
          2 => {name: "markup.underline.link.twiki"},
          3 => {name: "punctuation.definition.link.twiki"},
          4 => {name: "punctuation.definition.link.twiki"},
          5 => {name: "string.other.link.title.twiki"},
          6 => {name: "punctuation.definition.link.twiki"}},
        match: /(?<_1>\[)(?<_2>[^\]]*)(?<_3>\]) *(?<_4>\[)(?<_5>.*?)(?<_6>\])/,
        name: "meta.link.inline"}]},
   :"list-paragraph" => 
    {patterns: 
      [{begin: /\G\s+\S/,
        end: "^\\s*$",
        name: "markup.list.unnumbered.paragraph",
        patterns: [{include: "#inline"}, {include: "text.html.basic"}]}]},
   :"numlist-paragraph" => 
    {patterns: 
      [{begin: /\G\s+\S/,
        end: "^\\s*$",
        name: "markup.list.numbered.paragraph",
        patterns: [{include: "#inline"}, {include: "text.html.basic"}]}]}},
 scopeName: "text.html.twiki",
 uuid: "B2FD7223-BE64-4134-B43D-F7443EA54CCD"}
