module VER
  # This is used to represent events.
  # It also represents the minimum required properties for events.
  #
  # The reason we don't use the default Tk::Event::Data is to compensate for
  # differences of platforms and to have correct values for the event even if
  # we generate them in specs.
  class Event < Struct.new(:pattern, :keysym, :unicode)
    PATTERN = {}
    UNICODE  = Hash.new{|h,k| h[k] = Set.new }
    KEYSYM   = Hash.new{|h,k| h[k] = Set.new }

    WINDOWING_SYSTEM = Tk::TkCmd.windowingsystem
    MODIFIERS = %w[
      Control
      Meta M
      Mod1 M1 Command
      Mod2 M2 Option
      Mod3 M3
      Mod4 M4
      Mod5 M5
      Alt
      Shift
      Lock
      Extended
      Button1 B1
      Button2 B2
      Button3 B3
      Button4 B4
      Button5 B5
      Double
      Triple
      Quadruple
    ]

    def self.each(&block)
      PATTERN.values.each(&block)
    end

    def self.keysym(keysym, unicode = '')
      event = pattern("<#{keysym}>", keysym, unicode)
      MODIFIERS.each{|mod| pattern("<#{mod}-#{keysym}>", keysym, unicode) }
      event
    end

    def self.literal(keysym, unicode = keysym)
    end

    def self.pattern(pattern, keysym, unicode)
      event = new(pattern, keysym, unicode)
      PATTERN[event.pattern] = event
      UNICODE[event.unicode] << event
      KEYSYM[event.keysym] << event
      event
    end

    def self.fake(alias_pattern, keysym, unicode = '')
      event = pattern("<#{alias_pattern}>", keysym, unicode)
      MODIFIERS.each{|mod| pattern("<#{mod}-#{alias_pattern}>", keysym, unicode) }
      event
    end

    # given a <pattern>, this returns the event for this pattern.
    # given a unicode char, returns the event with shortest pattern.
    def self.[](string)
      if string =~ /^<(.*)>$/
        PATTERN.fetch(string)
      elsif string.size == 1
        UNICODE.fetch(string).min_by{|event| event.pattern.size }
      else # it may be keysym, but let's try to make it pattern instead
        PATTERN.fetch("<#{string}>")
      end
    rescue KeyError => ex
      raise(KeyError, "#{ex}: %p" % [string])
    end

    def initialize(pattern, keysym = '', unicode = '')
      self.pattern = convert_pattern(pattern)
      self.keysym  = convert_keysym(keysym)
      self.unicode = convert_unicode(unicode)
    end

    # Adjust
    def convert_pattern(pattern)
      pattern
    end

    def convert_keysym(keysm)
      keysym
    end

    def convert_unicode(unicode)
      unicode
    end

    case WINDOWING_SYSTEM
    when :x11
      fake('Shift-Tab', 'ISO_Left_Tab', "\t")

      keysym "XF86_Switch_VT_1"
      keysym "XF86_Switch_VT_2"
      keysym "XF86_Switch_VT_3"
      keysym "XF86_Switch_VT_4"
      keysym "XF86_Switch_VT_5"
      keysym "XF86_Switch_VT_6"
      keysym "XF86_Switch_VT_7"
      keysym "XF86_Switch_VT_8"
      keysym "XF86_Switch_VT_9"
      keysym "XF86_Switch_VT_10"
      keysym "XF86_Switch_VT_11"
      keysym "XF86_Switch_VT_12"
      keysym "XF86_ClearGrab", "*"
      keysym "XF86_Next_VMode", "+"
      keysym "XF86_Prev_VMode", "-"
      keysym "XF86MonBrightnessDown"
      keysym "XF86_Ungrab", "/"
    when :aqua
      fake 'ISO_Left_Tab', 'Shift-Tab', "\t"
    when :win32
      fake 'ISO_Left_Tab', 'Shift-Tab', "\t"
    else
      raise "Unknown windowing system: %p" % [WINDOWING_SYSTEM]
    end

    [*'0'..'9', *'a'..'Z', *'A'..'Z'].each{|sym| keysym(sym, sym) }

    keysym 'ampersand', '&'
    keysym 'apostrophe', "'"
    keysym 'asciitilde', '~'
    keysym 'asterisk', '*'
    keysym "at", "@"
    keysym "backslash", "\\"
    keysym "BackSpace", "\b"
    keysym "bar", "|"
    keysym "braceleft", "{"
    keysym "braceright", "}"
    keysym "bracketleft", "["
    keysym "bracketright", "]"

    def self.add(seq, sym, uni = nil)
      return unless uni
      case uni
      when /^[a-zA-Z0-9]$/
        if uni == sym
          puts "    literal %p" % [sym]
        else
          puts "    keysym %p, %p" % [sym, uni]
        end
      else
        puts "    pattern %p, %p, %p" % [seq, sym, uni]
      end
    end

    add "<Alt-Caps_Lock>", "Caps_Lock"
    add "<Alt-colon>", "colon", ":"
    add "<Alt-comma>", "comma", ","
    add "<Alt-Control_L>", "Control_L"
    add "<Alt-Control_R>", "Control_R"
    add "<Alt-D>", "D", "D"
    add "<Alt-d>", "d", "d"
    add "<Alt-Delete>", "Delete", "\x7F"
    add "<Alt-dollar>", "dollar", "$"
    add "<Alt-Down>", "Down"
    add "<Alt-E>", "E", "E"
    add "<Alt-e>", "e", "e"
    add "<Alt-Eisu_toggle>", "Eisu_toggle"
    add "<Alt-End>", "End"
    add "<Alt-equal>", "equal", "="
    add "<Alt-Escape>", "Escape", "\e"
    add "<Alt-exclam>", "exclam", "!"
    add "<Alt-F>", "F", "F"
    add "<Alt-f>", "f", "f"
    add "<Alt-G>", "G", "G"
    add "<Alt-g>", "g", "g"
    add "<Alt-grave>", "grave", "`"
    add "<Alt-greater>", "greater", ">"
    add "<Alt-H>", "H", "H"
    add "<Alt-h>", "h", "h"
    add "<Alt-Henkan_Mode>", "Henkan_Mode"
    add "<Alt-Home>", "Home"
    add "<Alt-I>", "I", "I"
    add "<Alt-i>", "i", "i"
    add "<Alt-Insert>", "Insert", ""
    add "<Alt-J>", "J", "J"
    add "<Alt-j>", "j", "j"
    add "<Alt-K>", "K", "K"
    add "<Alt-k>", "k", "k"
    add "<Alt-Kanji>", "Kanji", ""
    add "<Alt-KP_Add>", "KP_Add", "+"
    add "<Alt-KP_Begin>", "KP_Begin", "5"
    add "<Alt-KP_Delete>", "KP_Delete", "."
    add "<Alt-KP_Divide>", "KP_Divide", "/"
    add "<Alt-KP_Down>", "KP_Down", "2"
    add "<Alt-KP_End>", "KP_End", "1"
    add "<Alt-KP_Enter>", "KP_Enter", "\r"
    add "<Alt-KP_Home>", "KP_Home", "7"
    add "<Alt-KP_Insert>", "KP_Insert", "0"
    add "<Alt-KP_Left>", "KP_Left", "4"
    add "<Alt-KP_Multiply>", "KP_Multiply", "*"
    add "<Alt-KP_Next>", "KP_Next", "3"
    add "<Alt-KP_Prior>", "KP_Prior", "9"
    add "<Alt-KP_Right>", "KP_Right", "6"
    add "<Alt-KP_Subtract>", "KP_Subtract", "-"
    add "<Alt-KP_Up>", "KP_Up", "8"
    add "<Alt-L>", "L", "L"
    add "<Alt-l>", "l", "l"
    add "<Alt-Left>", "Left"
    add "<Alt-less>", "less", "<"
    add "<Alt-M>", "M", "M"
    add "<Alt-m>", "m", "m"
    add "<Alt-Menu>", "Menu"
    add "<Alt-Muhenkan>", "Muhenkan"
    add "<Alt-N>", "N", "N"
    add "<Alt-n>", "n", "n"
    add "<Alt-Next>", "Next"
    add "<Alt-numbersign>", "numbersign", "#"
    add "<Alt-O>", "O", "O"
    add "<Alt-o>", "o", "o"
    add "<Alt-P>", "P", "P"
    add "<Alt-p>", "p", "p"
    add "<Alt-parenleft>", "parenleft", "("
    add "<Alt-parenright>", "parenright", ")"
    add "<Alt-percent>", "percent", "%"
    add "<Alt-period>", "period", "."
    add "<Alt-plus>", "plus", "+"
    add "<Alt-Pointer_EnableKeys>", "Pointer_EnableKeys"
    add "<Alt-Print>", "Print"
    add "<Alt-Prior>", "Prior"
    add "<Alt-Q>", "Q", "Q"
    add "<Alt-q>", "q", "q"
    add "<Alt-question>", "question", "?"
    add "<Alt-quotedbl>", "quotedbl", "\""
    add "<Alt-R>", "R", "R"
    add "<Alt-r>", "r", "r"
    add "<Alt-Return>", "Return", "\r"
    add "<Alt-Right>", "Right"
    add "<Alt-Romaji>", "Romaji"
    add "<Alt-S>", "S", "S"
    add "<Alt-s>", "s", "s"
    add "<Alt-Scroll_Lock>", "Scroll_Lock"
    add "<Alt-semicolon>", "semicolon", ";"
    add "<Alt-Shift_L>", "Shift_L"
    add "<Alt-Shift_R>", "Shift_R"
    add "<Alt-slash>", "slash", "/"
    add "<Alt-space>", "space", " "
    add "<Alt-Super_L>", "Super_L"
    add "<Alt-T>", "T", "T"
    add "<Alt-t>", "t", "t"
    add "<Alt-Tab>", "Tab", "\t"
    add "<Alt-U>", "U", "U"
    add "<Alt-u>", "u", "u"
    add "<Alt-underscore>", "underscore", "_"
    add "<Alt-Up>", "Up"
    add "<Alt-V>", "V", "V"
    add "<Alt-v>", "v", "v"
    add "<Alt-W>", "W", "W"
    add "<Alt-w>", "w", "w"
    add "<Alt-X>", "X", "X"
    add "<Alt-x>", "x", "x"
    add "<Alt-Y>", "Y", "Y"
    add "<Alt-y>", "y", "y"
    add "<Alt-Z>", "Z", "z"
    add "<Alt-z>", "z", "z"
    add "<Alt-Zenkaku_Hankaku>", "Zenkaku_Hankaku"
    add "<Alt_L>", "Alt_L"
    add "<ampersand>", "ampersand", "&"
    add "<apostrophe>", "apostrophe", "'"
    add "<asciicircum>", "asciicircum", "^"
    add "<asciitilde>", "asciitilde", "~"
    add "<asterisk>", "asterisk", "*"
    add "<at>", "at", "@"
    add "<B>", "B", "B"
    add "<b>", "b", "b"
    add "<backslash>", "backslash", "\\"
    add "<BackSpace>", "BackSpace", "\b"
    add "<bar>", "bar", "|"
    add "<braceleft>", "braceleft", "{"
    add "<braceright>", "braceright", "}"
    add "<bracketleft>", "bracketleft", "["
    add "<bracketright>", "bracketright", "]"
    add "<Break>", "Break"
    add "<C>", "C", "C"
    add "<c>", "c", "c"
    add "<Caps_Lock>", "Caps_Lock"
    add "<colon>", "colon", ":"
    add "<comma>", "comma", ","
    add "<Control-0>", "0", "0"
    add "<Control-6>", "6", "\x1E"
    add "<Control-7>", "7", "\x1F"
    add "<Control-8>", "8", "\x7F"
    add "<Control-9>", "9", "9"
    add "<Control-A>", "A", "\x01"
    add "<Control-a>", "a", "\x01"
    add "<Control-Alt-0>", "0", "0"
    add "<Control-Alt-6>", "6", "\x1E"
    add "<Control-Alt-7>", "7", "\x1F"
    add "<Control-Alt-8>", "8", "\x7F"
    add "<Control-Alt-9>", "9", "9"
    add "<Control-Alt-A>", "A", "\x01"
    add "<Control-Alt-a>", "a", "\x01"
    add "<Control-Alt-ampersand>", "ampersand", "&"
    add "<Control-Alt-apostrophe>", "apostrophe", "'"
    add "<Control-Alt-asciicircum>", "asciicircum", "\x1E"
    add "<Control-Alt-asciitilde>", "asciitilde", "\x1E"
    add "<Control-Alt-asterisk>", "asterisk", "*"
    add "<Control-Alt-at>", "at"
    add "<Control-Alt-B>", "B", "\x02"
    add "<Control-Alt-b>", "b", "\x02"
    add "<Control-Alt-backslash>", "backslash", "\x1C"
    add "<Control-Alt-BackSpace>", "BackSpace", "\b"
    add "<Control-Alt-bar>", "bar", "\x1C"
    add "<Control-Alt-braceleft>", "braceleft", "\e"
    add "<Control-Alt-braceright>", "braceright", "\x1D"
    add "<Control-Alt-bracketleft>", "bracketleft", "\e"
    add "<Control-Alt-bracketright>", "bracketright", "\x1D"
    add "<Control-Alt-Break>", "Break"
    add "<Control-Alt-C>", "C", "\x03"
    add "<Control-Alt-c>", "c", "\x03"
    add "<Control-Alt-colon>", "colon", ":"
    add "<Control-Alt-comma>", "comma", ","
    add "<Control-Alt-Control-Alt-asciitilde>", "asciitilde", "\x1E"
    add "<Control-Alt-Control-Alt-bar>", "bar", "\x1C"
    add "<Control-Alt-Control-Alt-H>", "H", "\b"
    add "<Control-Alt-Control-Alt-Kanji>", "Kanji"
    add "<Control-Alt-Control-Alt-Romaji>", "Romaji"
    add "<Control-Alt-Control_R>", "Control_R"
    add "<Control-Alt-D>", "D", "\x04"
    add "<Control-Alt-d>", "d", "\x04"
    add "<Control-Alt-Delete>", "Delete", "\x7F"
    add "<Control-Alt-dollar>", "dollar", "$"
    add "<Control-Alt-Down>", "Down"
    add "<Control-Alt-E>", "E", "\x05"
    add "<Control-Alt-e>", "e", "\x05"
    add "<Control-Alt-Eisu_toggle>", "Eisu_toggle"
    add "<Control-Alt-equal>", "equal", "="
    add "<Control-Alt-Escape>", "Escape", "\e"
    add "<Control-Alt-exclam>", "exclam", "!"
    add "<Control-Alt-F>", "F", "\x06"
    add "<Control-Alt-f>", "f", "\x06"
    add "<Control-Alt-G>", "G", "\a"
    add "<Control-Alt-g>", "g", "\a"
    add "<Control-Alt-grave>", "grave"
    add "<Control-Alt-greater>", "greater", ">"
    add "<Control-Alt-H>", "H", "\b"
    add "<Control-Alt-h>", "h", "\b"
    add "<Control-Alt-Henkan_Mode>", "Henkan_Mode"
    add "<Control-Alt-Hiragana_Katakana>", "Hiragana_Katakana"
    add "<Control-Alt-I>", "I", "\t"
    add "<Control-Alt-i>", "i", "\t"
    add "<Control-Alt-Insert>", "Insert"
    add "<Control-Alt-J>", "J", "\n"
    add "<Control-Alt-j>", "j", "\n"
    add "<Control-Alt-K>", "K", "\v"
    add "<Control-Alt-k>", "k", "\v"
    add "<Control-Alt-Kanji>", "Kanji", ""
    add "<Control-Alt-KP_0>", "KP_0", ""
    add "<Control-Alt-KP_1>", "KP_1", ""
    add "<Control-Alt-KP_2>", "KP_2", ""
    add "<Control-Alt-KP_3>", "KP_3", ""
    add "<Control-Alt-KP_4>", "KP_4", ""
    add "<Control-Alt-KP_5>", "KP_5", ""
    add "<Control-Alt-KP_6>", "KP_6", ""
    add "<Control-Alt-KP_7>", "KP_7", ""
    add "<Control-Alt-KP_8>", "KP_8", ""
    add "<Control-Alt-KP_9>", "KP_9", ""
    add "<Control-Alt-KP_Begin>", "KP_Begin", "\x1D"
    add "<Control-Alt-KP_Decimal>", "KP_Decimal"
    add "<Control-Alt-KP_Delete>", "KP_Delete", "."
    add "<Control-Alt-KP_Down>", "KP_Down"
    add "<Control-Alt-KP_End>", "KP_End", "1"
    add "<Control-Alt-KP_Enter>", "KP_Enter", "\r"
    add "<Control-Alt-KP_Home>", "KP_Home", "\x1F"
    add "<Control-Alt-KP_Insert>", "KP_Insert", "0"
    add "<Control-Alt-KP_Left>", "KP_Left", "\x1C"
    add "<Control-Alt-KP_Next>", "KP_Next", "\e"
    add "<Control-Alt-KP_Prior>", "KP_Prior", "9"
    add "<Control-Alt-KP_Right>", "KP_Right", "\x1E"
    add "<Control-Alt-KP_Up>", "KP_Up", "\x7F"
    add "<Control-Alt-L>", "L", "\f"
    add "<Control-Alt-l>", "l", "\f"
    add "<Control-Alt-Left>", "Left"
    add "<Control-Alt-less>", "less", "<"
    add "<Control-Alt-M>", "M", "\r"
    add "<Control-Alt-m>", "m", "\r"
    add "<Control-Alt-Menu>", "Menu"
    add "<Control-Alt-minus>", "minus", "-"
    add "<Control-Alt-Muhenkan>", "Muhenkan"
    add "<Control-Alt-N>", "N", "\x0E"
    add "<Control-Alt-n>", "n", "\x0E"
    add "<Control-Alt-numbersign>", "numbersign", "#"
    add "<Control-Alt-O>", "O", "\x0F"
    add "<Control-Alt-o>", "o", "\x0F"
    add "<Control-Alt-P>", "P", "\x10"
    add "<Control-Alt-p>", "p", "\x10"
    add "<Control-Alt-parenleft>", "parenleft", "("
    add "<Control-Alt-parenright>", "parenright", ")"
    add "<Control-Alt-percent>", "percent", "%"
    add "<Control-Alt-period>", "period", "."
    add "<Control-Alt-plus>", "plus", "+"
    add "<Control-Alt-Pointer_EnableKeys>", "Pointer_EnableKeys"
    add "<Control-Alt-Q>", "Q", "\x11"
    add "<Control-Alt-q>", "q", "\x11"
    add "<Control-Alt-question>", "question", "?"
    add "<Control-Alt-quotedbl>", "quotedbl", "\""
    add "<Control-Alt-R>", "R", "\x12"
    add "<Control-Alt-r>", "r", "\x12"
    add "<Control-Alt-Return>", "Return", "\r"
    add "<Control-Alt-Right>", "Right"
    add "<Control-Alt-Romaji>", "Romaji"
    add "<Control-Alt-S>", "S", "\x13"
    add "<Control-Alt-s>", "s", "\x13"
    add "<Control-Alt-semicolon>", "semicolon", ";"
    add "<Control-Alt-Shift_L>", "Shift_L"
    add "<Control-Alt-Shift_R>", "Shift_R"
    add "<Control-Alt-slash>", "slash", "\x1F"
    add "<Control-Alt-space>", "space"
    add "<Control-Alt-Super_L>", "Super_L"
    add "<Control-Alt-T>", "T", "\x14"
    add "<Control-Alt-t>", "t", "\x14"
    add "<Control-Alt-Tab>", "Tab", "\t"
    add "<Control-Alt-U>", "U", "\x15"
    add "<Control-Alt-u>", "u", "\x15"
    add "<Control-Alt-underscore>", "underscore", "\x1F"
    add "<Control-Alt-Up>", "Up"
    add "<Control-Alt-V>", "V", "\x16"
    add "<Control-Alt-v>", "v", "\x16"
    add "<Control-Alt-W>", "W", "\x17"
    add "<Control-Alt-w>", "w", "\x17"
    add "<Control-Alt-X>", "X", "\x18"
    add "<Control-Alt-x>", "x", "\x18"
    add "<Control-Alt-Y>", "Y", "\x19"
    add "<Control-Alt-y>", "y", "\x19"
    add "<Control-Alt-Z>", "Z", "\x1A"
    add "<Control-Alt-z>", "z", "\x1A"
    add "<Control-Alt-Zenkaku_Hankaku>", "Zenkaku_Hankaku"
    add "<Control-Alt_L>", "Alt_L"
    add "<Control-ampersand>", "ampersand", "&"
    add "<Control-apostrophe>", "apostrophe", "'"
    add "<Control-asciicircum>", "asciicircum", "\x1E"
    add "<Control-asciitilde>", "asciitilde", "\x1E"
    add "<Control-asterisk>", "asterisk", "*"
    add "<Control-at>", "at"
    add "<Control-B>", "B", "\x02"
    add "<Control-b>", "b", "\x02"
    add "<Control-backslash>", "backslash", "\x1C"
    add "<Control-BackSpace>", "BackSpace", "\b"
    add "<Control-bar>", "bar", "\x1C"
    add "<Control-braceleft>", "braceleft", "\e"
    add "<Control-braceright>", "braceright", "\x1D"
    add "<Control-bracketleft>", "bracketleft", "\e"
    add "<Control-bracketright>", "bracketright", "\x1D"
    add "<Control-Break>", "Break"
    add "<Control-C>", "C", "\x03"
    add "<Control-c>", "c", "\x03"
    add "<Control-Caps_Lock>", "Caps_Lock"
    add "<Control-colon>", "colon", ":"
    add "<Control-comma>", "comma", ","
    add "<Control-Control-Z>", "Z", "\x1A"
    add "<Control-Control_R>", "Control_R"
    add "<Control-D>", "D", "\x04"
    add "<Control-d>", "d", "\x04"
    add "<Control-Delete>", "Delete", "\x7F"
    add "<Control-dollar>", "dollar", "$"
    add "<Control-Down>", "Down"
    add "<Control-E>", "E", "\x05"
    add "<Control-e>", "e", "\x05"
    add "<Control-Eisu_toggle>", "Eisu_toggle"
    add "<Control-End>", "End"
    add "<Control-equal>", "equal", "="
    add "<Control-Escape>", "Escape", "\e"
    add "<Control-exclam>", "exclam", "!"
    add "<Control-F10>", "F10"
    add "<Control-F11>", "F11"
    add "<Control-F12>", "F12"
    add "<Control-F1>", "F1"
    add "<Control-F2>", "F2"
    add "<Control-F3>", "F3"
    add "<Control-F4>", "F4"
    add "<Control-F5>", "F5"
    add "<Control-F6>", "F6"
    add "<Control-F7>", "F7"
    add "<Control-F8>", "F8"
    add "<Control-F9>", "F9"
    add "<Control-F>", "F", "\x06"
    add "<Control-f>", "f", "\x06"
    add "<Control-G>", "G", "\a"
    add "<Control-g>", "g", "\a"
    add "<Control-grave>", "grave"
    add "<Control-greater>", "greater", ">"
    add "<Control-H>", "H", "\b"
    add "<Control-h>", "h", "\b"
    add "<Control-Henkan_Mode>", "Henkan_Mode"
    add "<Control-Hiragana_Katakana>", "Hiragana_Katakana"
    add "<Control-Home>", "Home"
    add "<Control-I>", "I", "\t"
    add "<Control-i>", "i", "\t"
    add "<Control-Insert>", "Insert", ""
    add "<Control-J>", "J", "\n"
    add "<Control-j>", "j", "\n"
    add "<Control-K>", "K", "\v"
    add "<Control-k>", "k", "\v"
    add "<Control-Kanji>", "Kanji", ""
    add "<Control-KP_0>", "KP_0", ""
    add "<Control-KP_1>", "KP_1", ""
    add "<Control-KP_2>", "KP_2", ""
    add "<Control-KP_3>", "KP_3", ""
    add "<Control-KP_4>", "KP_4", ""
    add "<Control-KP_5>", "KP_5", ""
    add "<Control-KP_6>", "KP_6", ""
    add "<Control-KP_7>", "KP_7", ""
    add "<Control-KP_8>", "KP_8", ""
    add "<Control-KP_9>", "KP_9", ""
    add "<Control-KP_Add>", "KP_Add", "+"
    add "<Control-KP_Begin>", "KP_Begin", "\x1D"
    add "<Control-KP_Decimal>", "KP_Decimal"
    add "<Control-KP_Delete>", "KP_Delete", "."
    add "<Control-KP_Divide>", "KP_Divide", "/"
    add "<Control-KP_Down>", "KP_Down"
    add "<Control-KP_End>", "KP_End", "1"
    add "<Control-KP_Enter>", "KP_Enter", "\r"
    add "<Control-KP_Home>", "KP_Home", "\x1F"
    add "<Control-KP_Insert>", "KP_Insert", "0"
    add "<Control-KP_Left>", "KP_Left", "\x1C"
    add "<Control-KP_Multiply>", "KP_Multiply", "*"
    add "<Control-KP_Next>", "KP_Next", "\e"
    add "<Control-KP_Prior>", "KP_Prior", "9"
    add "<Control-KP_Right>", "KP_Right", "\x1E"
    add "<Control-KP_Subtract>", "KP_Subtract", "-"
    add "<Control-KP_Up>", "KP_Up", "\x7F"
    add "<Control-L>", "L", "\f"
    add "<Control-l>", "l", "\f"
    add "<Control-Left>", "Left"
    add "<Control-less>", "less", "<"
    add "<Control-M>", "M", "\r"
    add "<Control-m>", "m", "\r"
    add "<Control-Menu>", "Menu"
    add "<Control-Meta_L>", "Meta_L"
    add "<Control-minus>", "minus", "-"
    add "<Control-Muhenkan>", "Muhenkan"
    add "<Control-N>", "N", "\x0E"
    add "<Control-n>", "n", "\x0E"
    add "<Control-Next>", "Next"
    add "<Control-numbersign>", "numbersign", "#"
    add "<Control-Num_Lock>", "Num_Lock"
    add "<Control-O>", "O", "\x0F"
    add "<Control-o>", "o", "\x0F"
    add "<Control-P>", "P", "\x10"
    add "<Control-p>", "p", "\x10"
    add "<Control-parenleft>", "parenleft", "("
    add "<Control-parenright>", "parenright", ")"
    add "<Control-Pause>", "Pause"
    add "<Control-percent>", "percent", "%"
    add "<Control-period>", "period", "."
    add "<Control-plus>", "plus", "+"
    add "<Control-Pointer_EnableKeys>", "Pointer_EnableKeys"
    add "<Control-Prior>", "Prior"
    add "<Control-Q>", "Q", "\x11"
    add "<Control-q>", "q", "\x11"
    add "<Control-question>", "question", "?"
    add "<Control-quotedbl>", "quotedbl", "\""
    add "<Control-R>", "R", "\x12"
    add "<Control-r>", "r", "\x12"
    add "<Control-Return>", "Return", "\r"
    add "<Control-Right>", "Right"
    add "<Control-Romaji>", "Romaji"
    add "<Control-S>", "S", "\x13"
    add "<Control-s>", "s", "\x13"
    add "<Control-Scroll_Lock>", "Scroll_Lock"
    add "<Control-semicolon>", "semicolon", ";"
    add "<Control-Shift_L>", "Shift_L"
    add "<Control-Shift_R>", "Shift_R"
    add "<Control-slash>", "slash", "\x1F"
    add "<Control-space>", "space"
    add "<Control-Super_L>", "Super_L"
    add "<Control-T>", "T", "\x14"
    add "<Control-t>", "t", "\x14"
    add "<Control-Tab>", "Tab", "\t"
    add "<Control-U>", "U", "\x15"
    add "<Control-u>", "u", "\x15"
    add "<Control-underscore>", "underscore", "\x1F"
    add "<Control-Up>", "Up"
    add "<Control-V>", "V", "\x16"
    add "<Control-v>", "v", "\x16"
    add "<Control-W>", "W", "\x17"
    add "<Control-w>", "w", "\x17"
    add "<Control-X>", "X", "\x18"
    add "<Control-x>", "x", "\x18"
    add "<Control-Y>", "Y", "\x19"
    add "<Control-y>", "y", "\x19"
    add "<Control-Z>", "Z", "\x1A"
    add "<Control-z>", "z", "\x1A"
    add "<Control-Zenkaku_Hankaku>", "Zenkaku_Hankaku"
    add "<Control_L>", "Control_L"
    add "<Control_R>", "Control_R"
    add "<D>", "D", "D"
    add "<d>", "d", "d"
    add "<Delete>", "Delete", "\x7F"
    add "<dollar>", "dollar", "$"
    add "<Down>", "Down"
    add "<E>", "E", "E"
    add "<e>", "e", "e"
    add "<Eisu_toggle>", "Eisu_toggle"
    add "<End>", "End"
    add "<equal>", "equal", "="
    add "<Escape>", "Escape", "\e"
    add "<exclam>", "exclam", "!"
    add "<F10>", "F10"
    add "<F11>", "F11"
    add "<F12>", "F12"
    add "<F1>", "F1"
    add "<F2>", "F2"
    add "<F3>", "F3"
    add "<F4>", "F4"
    add "<F5>", "F5"
    add "<F6>", "F6"
    add "<F7>", "F7"
    add "<F8>", "F8"
    add "<F9>", "F9"
    add "<F>", "F", "F"
    add "<f>", "f", "f"
    add "<G>", "G", "G"
    add "<g>", "g", "g"
    add "<grave>", "grave", "`"
    add "<greater>", "greater", ">"
    add "<H>", "H", "H"
    add "<h>", "h", "h"
    add "<Henkan_Mode>", "Henkan_Mode"
    add "<Hiragana_Katakana>", "Hiragana_Katakana"
    add "<Home>", "Home"
    add "<I>", "I", "I"
    add "<i>", "i", "i"
    add "<Insert>", "Insert", ""
    add "<J>", "J", "J"
    add "<j>", "j", "j"
    add "<K>", "K", "K"
    add "<k>", "k", "k"
    add "<Kanji>", "Kanji", ""
    add "<KP_0>", "KP_0", ""
    add "<KP_1>", "KP_1", ""
    add "<KP_2>", "KP_2", ""
    add "<KP_3>", "KP_3", ""
    add "<KP_4>", "KP_4", ""
    add "<KP_5>", "KP_5", ""
    add "<KP_6>", "KP_6", ""
    add "<KP_7>", "KP_7", ""
    add "<KP_8>", "KP_8", ""
    add "<KP_9>", "KP_9", ""
    add "<KP_Add>", "KP_Add", "+"
    add "<KP_Begin>", "KP_Begin", "5"
    add "<KP_Decimal>", "KP_Decimal"
    add "<KP_Delete>", "KP_Delete", "."
    add "<KP_Divide>", "KP_Divide", "/"
    add "<KP_Down>", "KP_Down", "2"
    add "<KP_End>", "KP_End", "1"
    add "<KP_Enter>", "KP_Enter", "\r"
    add "<KP_Home>", "KP_Home", "7"
    add "<KP_Insert>", "KP_Insert", "0"
    add "<KP_Left>", "KP_Left", "4"
    add "<KP_Multiply>", "KP_Multiply", "*"
    add "<KP_Next>", "KP_Next", "3"
    add "<KP_Prior>", "KP_Prior", "9"
    add "<KP_Right>", "KP_Right", "6"
    add "<KP_Subtract>", "KP_Subtract", "-"
    add "<KP_Up>", "KP_Up", "8"
    add "<L>", "L", "L"
    add "<l>", "l", "l"
    add "<Left>", "Left"
    add "<less>", "less", "<"
    add "<M>", "M", "M"
    add "<m>", "m", "m"
    add "<Menu>", "Menu"
    add "<Meta_L>", "Meta_L"
    add "<minus>", "minus", "-"
    add "<Muhenkan>", "Muhenkan"
    add "<N>", "N", "N"
    add "<n>", "n", "n"
    add "<Next>", "Next"
    add "<numbersign>", "numbersign", "#"
    add "<Num_Lock>", "Num_Lock"
    add "<O>", "O", "O"
    add "<o>", "o", "o"
    add "<P>", "P", "P"
    add "<p>", "p", "p"
    add "<parenleft>", "parenleft", "("
    add "<parenright>", "parenright", ")"
    add "<Pause>", "Pause"
    add "<percent>", "percent", "%"
    add "<period>", "period", "."
    add "<plus>", "plus", "+"
    add "<Pointer_EnableKeys>", "Pointer_EnableKeys"
    add "<Print>", "Print"
    add "<Prior>", "Prior"
    add "<Q>", "Q", "Q"
    add "<q>", "q", "q"
    add "<question>", "question", "?"
    add "<quotedbl>", "quotedbl", "\""
    add "<R>", "R", "R"
    add "<r>", "r", "r"
    add "<Return>", "Return", "\r"
    add "<Right>", "Right"
    add "<Romaji>", "Romaji"
    add "<S>", "S", "S"
    add "<s>", "s", "s"
    add "<Scroll_Lock>", "Scroll_Lock"
    add "<semicolon>", "semicolon", ";"
    add "<Shift_L>", "Shift_L"
    add "<Shift_R>", "Shift_R"
    add "<Shift-Right>", "Right"
    add "<Shift-Left>", "Left"
    add "<Shift-Up>", "Up"
    add "<Shift-Down>", "Down"
    add "<Shift-Insert>", "Insert"
    add "<Shift-Control-Left>", "Left"
    add "<Shift-Control-Right>", "Right"
    add "<Shift-Home>", "Home"
    add "<Shift-End>", "Home"
    add "<Double-Tab>", "Tab", "\t"
    add "<Double-Tab>", "Tab", "\t"
    add "<Button-1>"
    add "<slash>", "slash", "/"
    add "<space>", "space", " "
    add "<Super_L>", "Super_L"
    add "<T>", "T", "T"
    add "<t>", "t", "t"
    add "<Tab>", "Tab", "\t"
    add "<U>", "U", "U"
    add "<u>", "u", "u"
    add "<underscore>", "underscore", "_"
    add "<Up>", "Up"
    add "<V>", "V", "V"
    add "<v>", "v", "v"
    add "<W>", "W", "W"
    add "<w>", "w", "w"
    add "<X>", "X", "X"
    add "<x>", "x", "x"
    add "<Y>", "Y", "Y"
    add "<y>", "y", "y"
    add "<Z>", "Z", "Z"
    add "<z>", "z", "z"
    add "<Zenkaku_Hankaku>", "Zenkaku_Hankaku"
  end
end
