VER::Syntax::LIST = {"ANTLR"=>[".antlr", ".g"],
 "ASP VB.net"=>[".asp vb.net", ".vb"],
 "ASP"=>[".asa", ".asp"],
 "ActionScript"=>[".actionscript", ".as"],
 "Ada"=>[".ada", ".adb", ".ads"],
 "Apache"=>[".apache", ".conf", ".htaccess"],
 "AppleScript"=>[".applescript", ".script editor"],
 "Bibtex"=>[".bib", ".bibtex"],
 "Blog (HTML)"=>[".blog (html)", ".blog.html"],
 "Blog (Markdown)"=>
  [".blog (markdown)",
   ".blog.markdown",
   ".blog.md",
   ".blog.mdown",
   ".blog.mkdn"],
 "Blog (Text)"=>[".blog (text)", ".blog.txt"],
 "Blog (Textile)"=>[".blog (textile)", ".blog.textile"],
 "Bulletin Board"=>[".bbcode", ".bulletin board"],
 "C++"=>
  [".c", ".c++", ".cc", ".cp", ".cpp", ".cxx", ".h", ".h++", ".hh", ".hpp"],
 "C"=>[".c", ".h"],
 "CSS"=>[".css", ".css.erb"],
 "DOT"=>[".dot"],
 "Diff"=>[".diff", ".patch"],
 "Dylan"=>[".dylan"],
 "Eiffel"=>[".e", ".eiffel"],
 "Erlang"=>[".erl", ".erlang", ".hrl"],
 "F-Script"=>[".f-script", ".fscript"],
 "FXScript"=>[".fxscript"],
 "Gri"=>[".gri"],
 "HTML (Mason)"=>
  [".autohandler", ".dhandler", ".html (mason)", ".mc", ".md", ".mhtml"],
 "HTML (Rails)"=>[".erb", ".html (rails)", ".html.erb", ".rhtml"],
 "HTML (Tcl)"=>[".adp", ".html (tcl)", ".inc", ".tcl"],
 "HTML for ASP.net"=>[".ascx", ".aspx", ".html for asp.net"],
 "HTML-ASP"=>[".asp", ".html-asp"],
 "HTML"=>
  [".ctp",
   ".htm",
   ".html",
   ".inc",
   ".php",
   ".phtml",
   ".shtml",
   ".tmpl",
   ".tpl",
   ".xhtml"],
 "Haskell"=>[".haskell", ".hs"],
 "Inform"=>[".inf", ".inform"],
 "Ini"=>[".conf", ".ini"],
 "Io"=>[".io"],
 "Java"=>[".bsh", ".java"],
 "JavaProperties"=>[".javaproperties", ".properties"],
 "JavaScript"=>[".htc", ".javascript", ".js", ".jsx"],
 "LaTeX Beamer"=>[".latex beamer"],
 "LaTeX Log"=>[".latex log"],
 "LaTeX"=>[".latex", ".tex"],
 "Lighttpd"=>[".lighttpd"],
 "Lisp"=>[".cl", ".el", ".l", ".lisp", ".mud"],
 "Literate Haskell"=>[".lhs", ".literate haskell"],
 "Logtalk"=>[".config", ".lgt", ".logtalk"],
 "Lua"=>[".lua"],
 "M"=>[".m"],
 "MEL"=>[".as", ".mel"],
 "MIPS"=>[".asm", ".mips", ".s", ".spim"],
 "Mail"=>[".mail"],
 "Makefile"=>[".gnumakefile", ".makefile", ".ocamlmakefile"],
 "Markdown"=>[".markdn", ".markdown", ".md", ".mdown"],
 "Modula-3"=>[".cm3", ".m3", ".modula-3"],
 "Movable Type"=>[".movable type", ".mtml"],
 "OCaml"=>[".ml", ".mli", ".ocaml"],
 "Objective-C++"=>[".h", ".m", ".mm", ".objective-c++"],
 "OpenGL"=>[".opengl"],
 "PHP"=>[".php"],
 "Pascal"=>[".p", ".pas", ".pascal"],
 "Perl"=>[".perl", ".pl", ".pm", ".pod", ".t"],
 "Plain text"=>[".plain text", ".txt"],
 "Processing"=>[".pde", ".processing"],
 "Quake3 Config"=>[".cfg", ".quake3 config"],
 "R"=>[".r", ".rprofile", ".s"],
 "Rez"=>[".r", ".rez"],
 "Ruby on Rails"=>[".builder", ".rb", ".ruby on rails", ".rxml"],
 "Ruby"=>
  [".capfile",
   ".cgi",
   ".fcgi",
   ".gemspec",
   ".irbrc",
   ".rake",
   ".rakefile",
   ".rb",
   ".rbx",
   ".rjs",
   ".ruby"],
 "SQL (Rails)"=>[".erbsql", ".sql (rails)", ".sql.erb"],
 "SQL"=>[".ddl", ".dml", ".sql"],
 "SWIG"=>[".i", ".swg", ".swig"],
 "Scheme"=>[".sch", ".scheme", ".scm"],
 "Shell-Unix-Generic"=>
  ["..textmate_init",
   ".bash_login",
   ".bash_logout",
   ".bash_profile",
   ".bashrc",
   ".profile",
   ".sh",
   ".shell-unix-generic",
   ".ss"],
 "Slate"=>[".slate"],
 "Smarty"=>[".smarty"],
 "Standard ML"=>[".sig", ".sml", ".standard ml"],
 "Subversion commit message"=>
  [".subversion commit message", ".svn-commit.2.tmp", ".svn-commit.tmp"],
 "Tcl"=>[".tcl"],
 "TeX Math"=>[".tex math"],
 "TeX"=>[".cls", ".sty", ".tex"],
 "Textile"=>[".textile"],
 "Twiki"=>[".twiki"],
 "Vectorscript"=>[".vectorscript", ".vss"],
 "XML strict"=>[".xml strict"],
 "XML"=>[".cpt", ".dtml", ".jsp", ".opml", ".pt", ".rss", ".tld", ".xml"],
 "XSL"=>[".xsl", ".xslt"],
 "YAML"=>[".yaml", ".yml"],
 "iCalendar"=>[".icalendar", ".ics", ".ifb"],
 "reStructuredText"=>[".rest", ".restructuredtext", ".rst"]}
