VER::Syntax::LIST = {"ANTLR"=>[".g"],
 "ASP VB.net"=>[".vb"],
 "ASP"=>[".asa"],
 "ActionScript"=>[".as"],
 "Ada"=>[".adb", ".ads"],
 "Apache"=>[".conf", ".htaccess"],
 "AppleScript"=>[".applescript", ".script editor"],
 "Bibtex"=>[".bib"],
 "Blog (HTML)"=>[".blog.html"],
 "Blog (Markdown)"=>
  [".blog.markdown", ".blog.md", ".blog.mdown", ".blog.mkdn"],
 "Blog (Text)"=>[".blog.txt"],
 "Blog (Textile)"=>[".blog.textile"],
 "Bulletin Board"=>[".bbcode"],
 "C++"=>
  [".C", ".c++", ".cc", ".cp", ".cpp", ".cxx", ".h", ".h++", ".hh", ".hpp"],
 "C"=>[".c", ".h"],
 "CSS"=>[".css", ".css.erb"],
 "DOT"=>[".DOT", ".dot"],
 "Diff"=>[".diff", ".patch"],
 "Dylan"=>[".dylan"],
 "Eiffel"=>[".e"],
 "Erlang"=>[".erl", ".hrl"],
 "F-Script"=>[".fscript"],
 "FXScript"=>[".fxscript"],
 "Gri"=>[".gri"],
 "HTML (Mason)"=>[".autohandler", ".dhandler", ".mc", ".md", ".mhtml"],
 "HTML (Rails)"=>[".erb", ".html.erb", ".rhtml"],
 "HTML (Tcl)"=>[".adp", ".inc", ".tcl"],
 "HTML for ASP.net"=>[".ascx", ".aspx"],
 "HTML-ASP"=>[".asp"],
 "HTML"=>
  [".ctp",
   ".htm",
   ".html",
   ".inc",
   ".php",
   ".phtml",
   ".shtml",
   ".tmpl",
   ".tpl",
   ".xhtml"],
 "Haskell"=>[".hs"],
 "Inform"=>[".inf"],
 "Ini"=>[".conf", ".ini"],
 "Io"=>[".io"],
 "Java"=>[".bsh", ".java"],
 "JavaProperties"=>[".properties"],
 "JavaScript"=>[".htc", ".js", ".jsx"],
 "LaTeX Beamer"=>[".LaTeX Beamer"],
 "LaTeX Log"=>[".LaTeX Log"],
 "LaTeX"=>[".tex"],
 "Lighttpd"=>[".Lighttpd"],
 "Lisp"=>[".cl", ".el", ".l", ".lisp", ".mud"],
 "Literate Haskell"=>[".lhs"],
 "Logtalk"=>[".config", ".lgt"],
 "Lua"=>[".lua"],
 "M"=>[".M"],
 "MEL"=>[".as"],
 "MIPS"=>[".asm", ".mips", ".s", ".spim"],
 "Mail"=>[".mail"],
 "Makefile"=>[".GNUmakefile", ".Makefile", ".OCamlMakefile", ".makefile"],
 "Markdown"=>[".markdn", ".markdown", ".md", ".mdown"],
 "Modula-3"=>[".cm3", ".m3"],
 "Movable Type"=>[".mtml"],
 "OCaml"=>[".ml", ".mli"],
 "Objective-C++"=>[".M", ".h", ".mm"],
 "OpenGL"=>[".OpenGL"],
 "PHP"=>[".PHP"],
 "Pascal"=>[".p", ".pas"],
 "Perl"=>[".PL", ".pl", ".pm", ".pod", ".t"],
 "Plain text"=>[".txt"],
 "Processing"=>[".pde"],
 "Quake3 Config"=>[".cfg"],
 "R"=>[".R", ".Rprofile", ".S", ".r", ".s"],
 "Rez"=>[".r"],
 "Ruby on Rails"=>[".builder", ".rb", ".rxml"],
 "Ruby"=>
  [".Rakefile",
   ".capfile",
   ".cgi",
   ".fcgi",
   ".gemspec",
   ".irbrc",
   ".rake",
   ".rb",
   ".rbx",
   ".rjs"],
 "SQL (Rails)"=>[".erbsql", ".sql.erb"],
 "SQL"=>[".ddl", ".dml", ".sql"],
 "SWIG"=>[".i", ".swg"],
 "Scheme"=>[".sch", ".scm"],
 "Shell-Unix-Generic"=>
  ["..textmate_init",
   ".bash_login",
   ".bash_logout",
   ".bash_profile",
   ".bashrc",
   ".profile",
   ".sh",
   ".ss"],
 "Slate"=>[".slate"],
 "Smarty"=>[".Smarty"],
 "Standard ML"=>[".sig", ".sml"],
 "Subversion commit message"=>[".svn-commit.2.tmp", ".svn-commit.tmp"],
 "Tcl"=>[".tcl"],
 "TeX Math"=>[".TeX Math"],
 "TeX"=>[".cls", ".sty"],
 "Textile"=>[".textile"],
 "Twiki"=>[".Twiki"],
 "Vectorscript"=>[".vss"],
 "XML strict"=>[".XML strict"],
 "XML"=>[".cpt", ".dtml", ".jsp", ".opml", ".pt", ".rss", ".tld", ".xml"],
 "XSL"=>[".xsl", ".xslt"],
 "YAML"=>[".yaml", ".yml"],
 "iCalendar"=>[".ics", ".ifb"],
 "reStructuredText"=>[".rest", ".rst"]}
