VER::Syntax::LIST = {"actionscript"=>[".actionscript", ".as"],
 "active4d"=>[".active4d"],
 "active4d_html"=>[".a4d", ".a4p", ".active4d_html"],
 "active4d_ini"=>[".active4d_ini", ".ini"],
 "active4d_library"=>[".a4l", ".active4d_library"],
 "ada"=>[".ada", ".adb", ".ads"],
 "antlr"=>[".antlr", ".g"],
 "apache"=>[".apache", ".conf", ".htaccess"],
 "applescript"=>[".applescript", ".script editor"],
 "asp"=>[".asa", ".asp"],
 "asp_vb.net"=>[".asp_vb.net", ".vb"],
 "bibtex"=>[".bib", ".bibtex"],
 "blog_html"=>[".blog.html", ".blog_html"],
 "blog_markdown"=>
  [".blog.markdown",
   ".blog.md",
   ".blog.mdown",
   ".blog.mkdn",
   ".blog_markdown"],
 "blog_text"=>[".blog.txt", ".blog_text"],
 "blog_textile"=>[".blog.textile", ".blog_textile"],
 "build"=>[".build"],
 "bulletin_board"=>[".bbcode", ".bulletin_board"],
 "c++"=>
  [".c", ".c++", ".cc", ".cp", ".cpp", ".cxx", ".h", ".h++", ".hh", ".hpp"],
 "c"=>[".c", ".h"],
 "cake"=>[".cake", ".thtml"],
 "camlp4"=>[".camlp4"],
 "cm"=>[".cm"],
 "coldfusion"=>[".cfc", ".cfm", ".cfml", ".coldfusion"],
 "context_free"=>[".cfdg", ".context free", ".context_free"],
 "cs"=>[".cs"],
 "css"=>[".css"],
 "css_experimental"=>[".css", ".css_experimental"],
 "csv"=>[".csv"],
 "d"=>[".d"],
 "diff"=>[".diff", ".patch"],
 "dokuwiki"=>[".dokuwiki"],
 "dot"=>[".dot"],
 "doxygen"=>[".doxygen"],
 "dylan"=>[".dylan"],
 "eiffel"=>[".e", ".eiffel"],
 "erlang"=>[".erl", ".erlang", ".hrl"],
 "f-script"=>[".f-script", ".fscript"],
 "fortran"=>
  [".dmod1", ".dt", ".f", ".f77", ".f90", ".f95", ".for", ".fortran", ".fpp"],
 "fxscript"=>[".fxscript"],
 "greasemonkey"=>[".greasemonkey", ".user.js"],
 "gri"=>[".gri"],
 "groovy"=>[".groovy", ".gvy"],
 "gtd"=>[".gtd"],
 "gtdalt"=>[".gtd", ".gtdalt", ".gtdlog"],
 "haml"=>[".haml", ".sass"],
 "haskell"=>[".haskell", ".hs"],
 "html-asp"=>[".asp", ".html-asp"],
 "html"=>
  [".htm",
   ".html",
   ".inc",
   ".php",
   ".phtml",
   ".shtml",
   ".tmpl",
   ".tpl",
   ".xhtml"],
 "html_django"=>[".html_django"],
 "html_for_asp.net"=>[".ascx", ".aspx", ".html_for_asp.net"],
 "html_mason"=>[".autohandler", ".dhandler", ".html_mason", ".mhtml"],
 "html_rails"=>[".html_rails", ".rhtml"],
 "html_tcl"=>[".adp", ".html_tcl", ".inc", ".tcl"],
 "icalendar"=>[".icalendar", ".ics", ".ifb"],
 "inform"=>[".inf", ".inform"],
 "ini"=>[".conf", ".ini"],
 "installer_distribution_script"=>[".dist", ".installer_distribution_script"],
 "io"=>[".io"],
 "java"=>[".bsh", ".java"],
 "javaproperties"=>[".javaproperties", ".properties"],
 "javascript"=>[".htc", ".javascript", ".js", ".jsx"],
 "javascript_+_prototype"=>[".javascript_+_prototype"],
 "javascript_+_prototype_bracketed"=>[".javascript_+_prototype_bracketed"],
 "jquery_javascript"=>[".jquery_javascript"],
 "json"=>[".json"],
 "languagedefinition"=>[".languagedefinition", ".textmate"],
 "latex"=>[".latex", ".tex"],
 "latex_beamer"=>[".latex_beamer"],
 "latex_log"=>[".latex_log"],
 "latex_memoir"=>[".latex_memoir"],
 "lexflex"=>[".l", ".lexflex"],
 "lighttpd"=>[".lighttpd"],
 "lilypond"=>[".ily", ".lilypond", ".ly"],
 "lisp"=>[".cl", ".el", ".l", ".lisp", ".mud"],
 "literate_haskell"=>[".lhs", ".literate_haskell"],
 "logo"=>[".logo"],
 "logtalk"=>[".config", ".lgt", ".logtalk"],
 "lua"=>[".lua"],
 "m"=>[".m"],
 "macports_portfile"=>[".macports_portfile"],
 "mail"=>[".mail"],
 "makefile"=>[".gnumakefile", ".makefile", ".ocamlmakefile"],
 "man"=>[".man"],
 "markdown"=>[".markdn", ".markdown", ".md", ".mdown"],
 "mediawiki"=>[".mediawiki", ".wiki", ".wikipedia"],
 "mel"=>[".as", ".mel"],
 "mips"=>[".asm", ".mips", ".s", ".spim"],
 "mod_perl"=>[".conf", ".mod_perl"],
 "modula-3"=>[".cm3", ".m3", ".modula-3"],
 "moinmoin"=>[".moinmoin"],
 "mootools"=>[".mootools"],
 "movable_type"=>[".movable_type", ".mtml"],
 "multimarkdown"=>[".multimarkdown"],
 "objective-c++"=>[".h", ".m", ".mm", ".objective-c++"],
 "objective-c"=>[".h", ".m", ".objective-c"],
 "ocaml"=>[".ml", ".mli", ".ocaml"],
 "ocamllex"=>[".mll", ".ocamllex"],
 "ocamlyacc"=>[".mly", ".ocamlyacc"],
 "opengl"=>[".opengl"],
 "pascal"=>[".p", ".pas", ".pascal"],
 "perl"=>[".perl", ".pl", ".pm", ".pod", ".t"],
 "php"=>[".php"],
 "plain_text"=>[".plain_text", ".txt"],
 "pmwiki"=>[".pmwiki"],
 "postscript"=>[".eps", ".postscript", ".ps"],
 "processing"=>[".pde", ".processing"],
 "prolog"=>[".prolog"],
 "property_list"=>
  [".dict",
   ".plist",
   ".property_list",
   ".savedsearch",
   ".scriptsuite",
   ".scriptterminology",
   ".tmcommand",
   ".tmdelta",
   ".tmdragcommand",
   ".tmlanguage",
   ".tmmacro",
   ".tmpreferences",
   ".tmsnippet",
   ".tmtheme"],
 "python"=>[".cpy", ".py", ".python", ".rpy", ".sconscript", ".sconstruct"],
 "python_django"=>[".python_django"],
 "qmake_project"=>[".pri", ".pro", ".qmake_project"],
 "qt_c++"=>[".cpp", ".h", ".qt_c++"],
 "quake3_config"=>[".cfg", ".quake3_config"],
 "r"=>[".r", ".rprofile", ".s"],
 "r_console"=>[".r_console"],
 "ragel"=>[".ragel", ".rl"],
 "rd_r_documentation"=>[".rd", ".rd_r_documentation"],
 "regexp"=>[".re", ".regexp"],
 "regular_expressions_oniguruma"=>[".re", ".regular_expressions_oniguruma"],
 "regular_expressions_python"=>[".re", ".regular_expressions_python"],
 "release_notes"=>[".release_notes", ".tmreleasenotes"],
 "remind"=>["..reminders", ".defs.rem", ".rem*.txt", ".remind"],
 "restructuredtext"=>[".rest", ".restructuredtext", ".rst"],
 "rez"=>[".r", ".rez"],
 "ruby"=>
  [".cgi",
   ".fcgi",
   ".gemspec",
   ".rake",
   ".rakefile",
   ".rb",
   ".rbx",
   ".rjs",
   ".ruby"],
 "ruby_experimental"=>[".ruby_experimental"],
 "ruby_on_rails"=>[".ruby_on_rails", ".rxml"],
 "s5"=>[".s5"],
 "scheme"=>[".sch", ".scheme", ".scm"],
 "scilab"=>[".dem", ".sce", ".sci", ".scilab", ".tst"],
 "setext"=>[".etx", ".etx.txt", ".setext"],
 "shell-unix-generic"=>
  [".bash_login",
   ".bash_logout",
   ".bash_profile",
   ".bashrc",
   ".profile",
   ".sh",
   ".shell-unix-generic",
   ".ss"],
 "slate"=>[".slate"],
 "smarty"=>[".smarty"],
 "sql"=>[".ddl", ".dml", ".sql"],
 "sql_rails"=>[".erbsql", ".sql_rails"],
 "ssh-config"=>[".config", ".ssh-config", ".ssh_config", ".sshd_config"],
 "standard_ml"=>[".sig", ".sml", ".standard_ml"],
 "strings_file"=>[".strings", ".strings_file"],
 "subversion_commit_message"=>
  [".subversion_commit_message", ".svn-commit.2.tmp", ".svn-commit.tmp"],
 "sweave"=>[".rnw", ".snw", ".sweave"],
 "swig"=>[".i", ".swg", ".swig"],
 "tcl"=>[".tcl"],
 "template_toolkit"=>[".template_toolkit", ".tt"],
 "tex"=>[".cls", ".sty", ".tex"],
 "tex_math"=>[".tex_math"],
 "textile"=>[".textile"],
 "tsv"=>[".tsv"],
 "twiki"=>[".twiki"],
 "txt2tags"=>[".t2t", ".txt2tags"],
 "vectorscript"=>[".vectorscript", ".vss"],
 "xhtml_1.0"=>[".xhtml_1.0"],
 "xml"=>[".cpt", ".dtml", ".jsp", ".opml", ".pt", ".rss", ".tld", ".xml"],
 "xml_strict"=>[".xml_strict"],
 "xsl"=>[".xsl", ".xslt"],
 "yaml"=>[".yaml", ".yml"],
 "yui_javascript"=>[".yui_javascript"]}
