# Encoding: UTF-8

{author: "William D. Neumann",
 name: "Slush & Poppies",
 settings: 
  [{settings: 
     {background: "#F1F1F1",
      caret: "#000000",
      foreground: "#000000",
      invisibles: "#BFBFBF",
      lineHighlight: "#00000026",
      selection: "#B0B0FF"}},
   {name: "Comment",
    scope: "comment",
    settings: {fontStyle: "", foreground: "#406040"}},
   {name: "String", scope: "string", settings: {foreground: "#C03030"}},
   {name: "Number",
    scope: "constant.numeric",
    settings: {foreground: "#0080A0"}},
   {name: "OCaml floating-point constants",
    scope: "source.ocaml constant.numeric.floating-point",
    settings: {fontStyle: "underline"}},
   {name: "Character constants",
    scope: "constant.character",
    settings: {foreground: "#800000"}},
   {name: "Built-in constant", scope: "constant.language", settings: {}},
   {name: "User-defined constant",
    scope: "constant.character, constant.other",
    settings: {}},
   {name: "Variable",
    scope: "variable.parameter, variable.other",
    settings: {}},
   {name: "Keyword",
    scope: "keyword",
    settings: {fontStyle: "", foreground: "#2060A0"}},
   {name: "Operators",
    scope: "keyword.operator",
    settings: {fontStyle: "", foreground: "#2060A0"}},
   {name: "OCaml prefix f-p operators",
    scope: "source.ocaml keyword.operator.symbol.prefix.floating-point",
    settings: {fontStyle: "underline"}},
   {name: "OCaml infix f-p operators",
    scope: "source.ocaml keyword.operator.symbol.infix.floating-point",
    settings: {fontStyle: "underline"}},
   {name: "Module Keyword",
    scope: "entity.name.module,  support.other.module",
    settings: {fontStyle: "", foreground: "#0080FF"}},
   {name: "Storage types",
    scope: "storage.type",
    settings: {foreground: "#A08000"}},
   {name: "Storage", scope: "storage", settings: {foreground: "#008080"}},
   {name: "Variant types",
    scope: "entity.name.class.variant",
    settings: {foreground: "#C08060"}},
   {name: "Directives",
    scope: "keyword.other.directive",
    settings: {fontStyle: "bold"}},
   {name: "Line-number directives",
    scope: "source.ocaml keyword.other.directive.line-number",
    settings: {fontStyle: ""}},
   {name: "Inherited class",
    scope: "entity.other.inherited-class",
    settings: {}},
   {name: "Function name",
    scope: "entity.name.function",
    settings: {fontStyle: "", foreground: "#800000"}},
   {name: "Type name",
    scope: "storage.type.user-defined",
    settings: {foreground: "#800080"}},
   {name: "Class type name",
    scope: "entity.name.type.class.type",
    settings: {foreground: "#8000C0"}},
   {name: "Function argument", scope: "variable.parameter", settings: {}},
   {name: "Tag name", scope: "entity.name.tag", settings: {}},
   {name: "Tag attribute", scope: "entity.other.attribute-name", settings: {}},
   {name: "Library function", scope: "support.function", settings: {}},
   {name: "Library constant", scope: "support.constant", settings: {}},
   {name: "Library class/type",
    scope: "support.type, support.class",
    settings: {}},
   {name: "Library variable", scope: "support.variable", settings: {}},
   {name: "Invalid", scope: "invalid", settings: {}}],
 uuid: "D68685B8-1CFE-4C10-99C4-E21CBC892376"}
