# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: 
   "echo \"<!-- gotAPI.com search widget v2 begin -->\n<body onload=\\\"init();\\\">\n<DIV>\n<STYLE>\n.gaMenu{border:1px solid #505050;background-color:#FAFAFA;padding:0px 5px 0px 5px;}\n.gaHeaderRow{font:bold 8pt Arial;color:#359155;border-top:1px solid #C0C0C0;width:250px;}\n.gaRegularRow,.gaFooterRow{font:8pt Arial;cursor:pointer;}\n.gaSelectedRow{font:8pt Arial;background-color:#c1e0e6;cursor:pointer;}\n</STYLE>\n<SCRIPT><!--\ngaMod='module_java15noui.js';gaTitle='J2SE v1.5 less UI';updateWhenLoaded=false;\nvar gaL=false;function gaInit(){if(gaL)return;gaL=true;var s=document.createElement('script');\ns.type='text/javascript';s.src='http://www.gotapi.com/widgets/compiled/c1_module_groovy.js.jsz';s.defer='defer';s.defered='yes';\ndocument.getElementById('gaInfo').parentNode.appendChild(s)}function gaSearching(){\ndocument.getElementById('gaWait').style.display='';updateWhenLoaded=true;\ndocument.getElementById('gaInfo').style.display='none'}\n//-->\n</SCRIPT>\n<DIV style='font:bold 10pt Arial'>Quick J2SE v1.5 less UI lookup</DIV>\n<INPUT id=gaSearch size=20 onfocus=\\\"gaInit()\\\" onkeydown=\\\"gaSearching()\\\">\n<DIV id=gaInfo style='font:7pt Arial'>powered by <A href='http://www.gotapi.com' style='padding:0px'>gotAPI.com</A></DIV>\n<DIV id=gaWait style='font:7pt Arial;display:none'>Searching...</DIV>\n</DIV>\n</body>\n<!-- gotAPI.com search widget v2 end -->\"\n\nif [ $TM_CURRENT_WORD ] \nthen\n\techo \"<script>function init() { document.getElementById('gaSearch').value = '$TM_CURRENT_WORD'; document.getElementById('gaSearch').focus(); gaSearching(); }</script>\"\nfi",
  input: "none",
  keyEquivalent: "^~h",
  name: "Documentation For Word (Groovy)",
  output: "showAsHTML",
  scope: "source.groovy",
  uuid: "6C65B168-6119-4AD2-9606-CE64FA90B0A2"},
 {beforeRunningCommand: "nop",
  command: 
   "echo \"<!-- gotAPI.com search widget v2 begin -->\n<body onload=\\\"init();\\\">\n<DIV>\n<STYLE>\n.gaMenu{border:1px solid #505050;background-color:#FAFAFA;padding:0px 5px 0px 5px;}\n.gaHeaderRow{font:bold 8pt Arial;color:#359155;border-top:1px solid #C0C0C0;width:250px;}\n.gaRegularRow,.gaFooterRow{font:8pt Arial;cursor:pointer;}\n.gaSelectedRow{font:8pt Arial;background-color:#c1e0e6;cursor:pointer;}\n</STYLE>\n<SCRIPT><!--\ngaMod='module_java15noui.js';gaTitle='J2SE v1.5 less UI';updateWhenLoaded=false;\nvar gaL=false;function gaInit(){if(gaL)return;gaL=true;var s=document.createElement('script');\ns.type='text/javascript';s.src='http://www.gotapi.com/widgets/compiled/c1_module_java15noui.js.jsz';s.defer='defer';s.defered='yes';\ndocument.getElementById('gaInfo').parentNode.appendChild(s)}function gaSearching(){\ndocument.getElementById('gaWait').style.display='';updateWhenLoaded=true;\ndocument.getElementById('gaInfo').style.display='none'}\n//-->\n</SCRIPT>\n<DIV style='font:bold 10pt Arial'>Quick J2SE v1.5 less UI lookup</DIV>\n<INPUT id=gaSearch size=20 onfocus=\\\"gaInit()\\\" onkeydown=\\\"gaSearching()\\\">\n<DIV id=gaInfo style='font:7pt Arial'>powered by <A href='http://www.gotapi.com' style='padding:0px'>gotAPI.com</A></DIV>\n<DIV id=gaWait style='font:7pt Arial;display:none'>Searching...</DIV>\n</DIV>\n</body>\n<!-- gotAPI.com search widget v2 end -->\"\n\nif [ $TM_CURRENT_WORD ] \nthen\n\techo \"<script>function init() { document.getElementById('gaSearch').value = '$TM_CURRENT_WORD'; document.getElementById('gaSearch').focus(); gaSearching(); }</script>\"\nfi",
  input: "none",
  keyEquivalent: "^h",
  name: "Documentation For Word (Java)",
  output: "showAsHTML",
  scope: "source.groovy",
  uuid: "E8B13A2B-C6AE-47C1-AD42-AD5B7A0B157E"},
 {beforeRunningCommand: "nop",
  command: 
   "require_cmd groovyConsole\n\n\"$DIALOG\" tooltip --text \"Opening GroovyConsole…\"\n\nosascript -e 'on openGroovyConsole()\n\tdo shell script \"groovyConsole > /dev/null 2>&1 &\"\nend openGroovyConsole\n\ntell application \"System Events\"\n\tset UI_enabled to UI elements enabled\nend tell\nif UI_enabled is false then\n\ttell application \"System Preferences\"\n\t\tactivate\n\t\tset current pane to ¬\n\t\t\tpane \"com.apple.preference.universalaccess\"\n\t\tset the dialog_message to \"This script utilizes \" & ¬\n\t\t\t\"the built-in Graphic User Interface Scripting \" & ¬\n\t\t\t\"architecture of Mac OS X \" & ¬\n\t\t\t\"which is currently disabled.\" & return & return & ¬\n\t\t\t\"You can activate GUI Scripting by selecting the \" & ¬\n\t\t\t\"checkbox “Enable access for assistive devices” \" & ¬\n\t\t\t\"in the Universal Access preference pane.\"\n\t\tdisplay dialog dialog_message buttons {\"OK\"} ¬\n\t\t\tdefault button 1 with icon 1\n\tend tell\nelse\n\ttell application \"System Events\"\n\t\tset theProcesses to every process whose name is \"java\"\n\t\tif (count of theProcesses) is 0 then\n\t\t\topenGroovyConsole() of me\n\t\telse\n\t\t\tset foundIt to false\n\t\t\trepeat with i from 1 to (count of theProcesses)\n\t\t\t\tset thisProcess to item i of theProcesses\n\t\t\t\ttry\n\t\t\t\t\ttell thisProcess\n\t\t\t\t\t\tset theWindow to (the window \"GroovyConsole\")\n\t\t\t\t\t\tset frontmost of thisProcess to true\n\t\t\t\t\t\tset foundIt to true\n\t\t\t\t\tend tell\n\t\t\t\ton error number 1\n\t\t\t\t\t-- do nothing\n\t\t\t\tend try\n\t\t\tend repeat\n\t\t\tif foundIt is false then\n\t\t\t\topenGroovyConsole() of me\n\t\t\tend if\n\t\tend if\n\tend tell\nend if\n\n'",
  fallbackInput: "none",
  input: "none",
  name: "Groovy Console",
  output: "discard",
  scope: "source.groovy",
  uuid: "951D524E-4CB0-4A71-91A5-4DCA57D6686D"},
 {beforeRunningCommand: "nop",
  command: 
   "echo \"<meta http-equiv='Refresh'\n        content='0;URL=http://groovy.codehaus.org/groovy-jdk/'>\"\n",
  input: "selection",
  keyEquivalent: "^~@h",
  name: "Groovy JDK",
  output: "showAsHTML",
  scope: "source.groovy",
  uuid: "78F26F76-76B4-400E-84F0-E22DB05063CD"},
 {beforeRunningCommand: "nop",
  command: "groovymate.sh",
  fallbackInput: "word",
  input: "document",
  keyEquivalent: "@r",
  name: "Run",
  output: "showAsHTML",
  scope: "source.groovy",
  uuid: "E9CD6C3E-DC99-4682-B98D-517D34C503A8"},
 {beforeRunningCommand: "nop",
  command: "export TM_GROOVYMATE_GET_ARGS=\ngroovymate.sh",
  fallbackInput: "word",
  input: "document",
  keyEquivalent: "@R",
  name: "Run (with args)",
  output: "showAsHTML",
  scope: "source.groovy",
  uuid: "3E6C0C17-C48E-4194-A99F-7365F48AE196"},
 {beforeRunningCommand: "nop",
  command: 
   "if [ \"$TM_SELECTED_TEXT\" == \"\" ]; then\n   exit_show_tool_tip \"select some code to run\"\nelse\n  \"$GROOVY_HOME/bin/groovy\" -e \"$TM_SELECTED_TEXT\"\n  exit_show_html\nfi\n\n",
  fallbackInput: "none",
  input: "selection",
  keyEquivalent: "~@r",
  name: "Run Selected Snippet",
  output: "showAsTooltip",
  scope: "source.groovy",
  uuid: "729F1599-08BE-40B0-93D6-0482FA566CC7"}]
