# Encoding: UTF-8

[{autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh clean",
  input: "none",
  keyEquivalent: "^@G",
  name: "Clean",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "81EFF7DA-D8FD-49D3-AD14-285E135CAA9D"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh war",
  input: "none",
  keyEquivalent: "^@G",
  name: "Create WAR",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "90AF1D77-BD5E-454C-A5E0-D8B19DA4089A"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh create",
  input: "none",
  keyEquivalent: "^@G",
  name: "Create …",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "ED4C9595-F749-4803-98BF-EA73357D8AE0"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" controller",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Controller",
  output: "showAsTooltip",
  scope: "source.groovy, text.html.grails",
  uuid: "F23B2416-2A90-4F89-8E53-79848D149E25"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" controller_test",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Controller Test",
  output: "showAsTooltip",
  scope: "source.groovy",
  uuid: "819737E6-F9B0-4C61-A5CE-1A9EF7B8C172"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" domain_class",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Domain Class",
  output: "showAsTooltip",
  scope: "source.groovy, text.html.grails",
  uuid: "F3547D2C-0CC0-45E1-BDCE-CFD4D45BED15"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" domain_class_test",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Domain Class Test",
  output: "showAsTooltip",
  scope: "source.groovy",
  uuid: "9DD9D0CD-7470-49A0-97B8-78852DF6D401"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" service",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Service",
  output: "showAsTooltip",
  scope: "source.groovy, text.html.grails",
  uuid: "B6320071-EA2B-4ABD-8BF0-4BF0481F2877"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" service_test",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Service Test",
  output: "showAsTooltip",
  scope: "source.groovy",
  uuid: "4933DBBB-1BFA-4EC7-B40E-F3AF80D54FEA"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" taglib",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Tag Lib",
  output: "showAsTooltip",
  scope: "source.groovy, text.html.grails",
  uuid: "4BBF0689-BAEE-4BC9-9272-73BD7705A79E"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" taglib_test",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To Tag Lib Test",
  output: "showAsTooltip",
  scope: "source.groovy",
  uuid: "A6E1AD30-CEA6-4632-A40C-092E48643B26"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" view",
  input: "none",
  keyEquivalent: "~@",
  name: "Go To View",
  output: "showAsTooltip",
  scope: "source.groovy",
  uuid: "0867DC60-0DD7-483A-86BA-07763BD2D8DB"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh install_plugin",
  input: "none",
  keyEquivalent: "^@G",
  name: "Install Plugin …",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "9B67E226-4E45-4DDD-99FC-31545A67B7B9"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh list_plugins",
  input: "none",
  keyEquivalent: "^@G",
  name: "List Plugins",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "A77539E3-ACBE-4AD4-9DE8-625340CBACC7"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh run_app",
  input: "none",
  keyEquivalent: "^@G",
  name: "Run App",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "FD3BEFAC-5C8C-4D03-9DF1-A07EB8B79807"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh run_grails_task",
  input: "none",
  keyEquivalent: "^@G",
  name: "Run Arbitrary Grails Task …",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "DEFDA7D4-BB3B-47D4-9408-C63C7A901A97"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "grailsmate_bootstrap.sh test_app",
  input: "none",
  keyEquivalent: "^@G",
  name: "Test App",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "CE0A3C0D-2E58-47B2-8271-F8FBA3846CB4"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: 
   "if [ \"$TM_SELECTED_FILES\" ]\nthen\n\teval grailsmate_bootstrap.sh focussed_test \"$TM_SELECTED_FILES\"\nelse\n\tgrailsmate_bootstrap.sh focussed_test \"$TM_FILEPATH\"\nfi",
  input: "none",
  keyEquivalent: "^@G",
  name: "Test App (selected)",
  output: "showAsHTML",
  scope: 
   "source.groovy, source.java, source.java-props, text.xml, text.html.grails",
  uuid: "2922A132-7A49-4193-B959-D30D817160B5"}]
