# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: 
   "#!/usr/bin/env python\n\nimport sys\nx = sys.stdin.read().strip()\nif x:\n\tsys.stdout.write(\"\\`%s\\`$0\" % x)\nelse:\n\tsys.stdout.write(\"\\`$1\\`$0\")\n",
  fallbackInput: "word",
  input: "selection",
  keyEquivalent: "^'",
  name: "Infix Function Call From Word / Selection",
  output: "insertAsSnippet",
  scope: "source.haskell",
  uuid: "FA4AA254-EB7D-4B43-AC67-066AA9E8E8D9"},
 {beforeRunningCommand: "nop",
  command: 
   "#!/bin/bash\n\nTHASKELL=${TM_HASKELL:-ghci}\n\nesc () {\nSTR=\"$1\" ruby <<\"RUBY\"\n   str = ENV['STR']\n   str = str.gsub(/'/, \"'\\\\\\\\''\")\n   str = str.gsub(/[\\\\\"]/, '\\\\\\\\\\\\0')\n   print \"'\#{str}'\"\nRUBY\n}\n\nosascript <<- APPLESCRIPT\ntell app \"Terminal\"\n\tlaunch\n\tactivate\n\tdo script \"clear; cd $(esc \"${TM_DIRECTORY}\"); ${THASKELL} $(esc \"${TM_FILEPATH}\")\"\n\tset position of first window to {100, 100}\nend tell\nAPPLESCRIPT\n",
  input: "none",
  keyEquivalent: "@R",
  name: "Load in GHCi",
  output: "showAsTooltip",
  scope: "source.haskell",
  uuid: "2242C46C-153E-4EEB-B80B-A5398559D759"},
 {beforeRunningCommand: "nop",
  command: 
   "echo \"<meta http-equiv=\\\"refresh\\\" content=\\\"0; http://haskell.org/hoogle/?q=${TM_SELECTED_TEXT:=$TM_CURRENT_WORD}\\\">\"",
  fallbackInput: "word",
  input: "none",
  keyEquivalent: "^H",
  name: "Lookup on Hoogle",
  output: "showAsHTML",
  scope: "source.haskell",
  uuid: "50D814AE-D850-4C97-AF3E-1FDE4366C6A3"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   ": ${TM_HASKELL:=runhaskell}\nrequire_cmd \"$TM_HASKELL\"\n\n\"$TM_HASKELL\" \"$TM_FILEPATH\" 2>&1 | haskellmate\n\n",
  input: "none",
  keyEquivalent: "@r",
  name: "Run",
  output: "showAsHTML",
  scope: "source.haskell",
  uuid: "3B083BE7-9812-4F06-A758-CCAD9514E797"},
 {beforeRunningCommand: "nop",
  command: "haskelltype \"${TM_SELECTED_TEXT:-$TM_CURRENT_WORD}\"",
  input: "none",
  keyEquivalent: "^h",
  name: "Show Type",
  output: "showAsTooltip",
  scope: "source.haskell",
  uuid: "6B723007-D4EE-476B-8282-76230C559D5A"}]
