# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: 
   "#!/usr/bin/env ruby\njs = STDIN.read\nputs <<-HTML\n<!-- howdy -->\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n  <title>Basic Javascript Test</title>\n  <script src=\"file://\#{ENV['TM_SUPPORT_PATH']}/script/prototype.js\" type=\"text/javascript\"></script>\n</head>\n<body>\n<script type=\"text/javascript\" charset=\"utf-8\">\ntry{\n//YOUR STUFF//\n//YOUR STUFF//\n//YOUR STUFF//\n\n\#{js}\n\n//YOUR STUFF//\n//YOUR STUFF//\n//YOUR STUFF//\n}catch(e){ document.write(e); throw(e) };\n</script>\n</body>\n</html>\nHTML\n",
  input: "selection",
  keyEquivalent: "@r",
  name: "Basic Prototype Javascript Test",
  output: "showAsHTML",
  scope: "source.js.prototype",
  uuid: "71838529-2441-4B3C-B9BD-B0CD115DD06C"},
 {beforeRunningCommand: "nop",
  bundleUUID: "467B298F-6227-11D9-BFB1-000D93589AF6",
  command: 
   "#!/usr/bin/env ruby\nrequire \"\#{ENV['TM_SUPPORT_PATH']}/lib/codecompletion\"\nTextmateCodeCompletion.simple('Prototype Completions')\n",
  fallbackInput: "line",
  input: "selection",
  keyEquivalent: "~",
  name: "CodeCompletion Javascript Prototype",
  output: "insertAsSnippet",
  scope: "source.js.prototype",
  uuid: "51D8677D-0D57-41A9-8C95-DC909C9F049B"},
 {beforeRunningCommand: "nop",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/html.sh\"\n\nredirect \"http://prototypejs.org/api/\"\n",
  input: "none",
  keyEquivalent: "^h",
  name: "Prototype Documentation",
  output: "showAsHTML",
  scope: "source.js.prototype",
  uuid: "8DCA2782-E6DE-4E86-A7F0-C4DA2B93A655"},
 {beforeRunningCommand: "nop",
  command: 
   "echo \"<meta http-equiv='Refresh'\n        content='0;URL=http://prototypejs.org/api/`echo ${TM_SELECTED_TEXT:-$TM_CURRENT_WORD}|sed 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`'>\"\n",
  fallbackInput: "word",
  input: "none",
  keyEquivalent: "^h",
  name: "Prototype Documentation for Class",
  output: "showAsHTML",
  scope: "source.js.prototype support.class.prototype",
  uuid: "F9F5D55E-6D17-46C8-8F3E-3A6E610F04FE"},
 {beforeRunningCommand: "nop",
  command: 
   "read sel\nif grep <<<${sel:-!} -Esq '[a-zA-Z0-9_\\.]+'\n\tthen exit_show_html \"<meta http-equiv='Refresh' content='0;URLhttp://wiki.script.aculo.us/scriptaculous/search/?page%5Bname%5D=$sel'>\"\n\telse echo \"Nothing to lookup (hint: place the caret on a function name)\"\nfi",
  fallbackInput: "scope",
  input: "selection",
  keyEquivalent: "^H",
  name: "Scriptaculous Documentation for Word",
  output: "showAsHTML",
  scope: "source.js.prototype",
  uuid: "D84F2D85-BE10-416A-BD9D-076AE6FDB436"}]
