# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: 
   "#!/usr/bin/env ruby -wKU\n\nSUPPORT = ENV['TM_SUPPORT_PATH']\n\nrequire SUPPORT + '/lib/escape'\nrequire SUPPORT + '/lib/exit_codes'\nrequire SUPPORT + '/lib/ui'\n\nwords = `grep \"^$TM_CURRENT_WORD\" \"$TM_BUNDLE_PATH/support/data/completions.txt\"`.split(\"\\n\")\nTextMate.exit_show_tool_tip \"No completion available\" if words.empty?\n\nif words.size > 1\n\n\ti = TextMate::UI.menu(words)\n\tTextMate.exit_discard() if i == nil\n\tchoice = words[i]\n\t\nelse\n\tchoice = words.pop\nend\n\nsnip = choice[ENV['TM_CURRENT_WORD'].length..-1]\n\ni=0\nprint snip.gsub( /([a-zA-Z0-9\\:\\.]+?)([,\\)])/ ) {\n\t\"${\" + String(i+=1) + \":\" + $1 + \"}\" + $2\n}",
  fallbackInput: "word",
  input: "none",
  keyEquivalent: "~",
  name: "Auto Complete Method / Property",
  output: "insertAsSnippet",
  scope: "source.js.jsfl",
  uuid: "C97C9490-30DF-4DC7-B5A1-9E3FA9691317"},
 {beforeRunningCommand: "nop",
  command: "asd.rb\n",
  fallbackInput: "word",
  input: "selection",
  keyEquivalent: "^h",
  name: "Documentation for Word / Selection",
  output: "discard",
  scope: "source.js.jsfl",
  uuid: "4E4934AC-F290-49DD-A424-14B2760666E7"},
 {beforeRunningCommand: "saveActiveFile",
  command: "open \"$TM_FILEPATH\"\n",
  input: "none",
  keyEquivalent: "@r",
  name: "Run",
  output: "discard",
  scope: "source.js.jsfl",
  uuid: "3ACF1061-FE40-4377-9514-70B83494946D"}]
