# Encoding: UTF-8

[{autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t clean",
  input: "none",
  keyEquivalent: "^@M",
  name: "Clean",
  output: "showAsHTML",
  uuid: "B1E0991E-106F-452B-8AA5-17564847EDA6"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t compile",
  input: "none",
  keyEquivalent: "^@M",
  name: "Compile",
  output: "showAsHTML",
  uuid: "BDD18676-3D30-41CD-A556-548838A41F3E"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t deploy",
  input: "none",
  keyEquivalent: "^@M",
  name: "Deploy",
  output: "showAsHTML",
  uuid: "A3443F7C-CBE3-4698-BE25-040AF1297E29"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t install",
  input: "none",
  keyEquivalent: "^@M",
  name: "Install",
  output: "showAsHTML",
  uuid: "A2EAF58E-7C18-4E5A-93B9-6C249696CAFD"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t integration-test",
  input: "none",
  keyEquivalent: "^@M",
  name: "Integration Test",
  output: "showAsHTML",
  uuid: "F1DA338C-FD12-4EFF-9BA6-67EFA3DCDFF3"},
 {beforeRunningCommand: "nop",
  command: 
   "settings=~/.m2/settings.xml\nif [ -f \"$settings\" ]\nthen\n\topen -a TextMate ~/.m2/settings.xml\nelse\n\tTextMate.exit_show_tooltip \"‘$settings’ does not exist\"\nfi ",
  input: "none",
  keyEquivalent: "^@S",
  name: "Open personal settings.xml",
  output: "showAsTooltip",
  uuid: "A69B943D-83B8-467E-A6AC-0CDF9A288EB9"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t package",
  input: "none",
  keyEquivalent: "^@M",
  name: "Package",
  output: "showAsHTML",
  uuid: "D421D75D-DBDE-4993-9686-E4208DD4A87E"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -P",
  input: "none",
  keyEquivalent: "^@M",
  name: "Profiles",
  output: "showAsTooltip",
  uuid: "E7EA03BE-2FE5-45E7-A0C6-64B0BBCBA738"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -p ",
  input: "none",
  keyEquivalent: "^@M",
  name: "Redo Previous Task",
  output: "showAsHTML",
  uuid: "862B0BB5-7D5D-42FC-BF41-E0A773A6590F"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t release:branch",
  input: "none",
  keyEquivalent: "^@M",
  name: "Release Branch",
  output: "showAsHTML",
  uuid: "1BFA4873-D0F9-47A1-B4D4-22325F5FD4F3"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t release:clean",
  input: "none",
  keyEquivalent: "^@M",
  name: "Release Clean",
  output: "showAsHTML",
  uuid: "9F2DDE9A-18C6-43B1-8F1C-A05776AF3663"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t release:perform",
  input: "none",
  keyEquivalent: "^@M",
  name: "Release Perform",
  output: "showAsHTML",
  uuid: "DBCA3485-7EAE-46DE-ADA7-1CB754F6A7A8"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t release:prepare",
  input: "none",
  keyEquivalent: "^@M",
  name: "Release Prepare",
  output: "showAsHTML",
  uuid: "73AF2F5B-353A-40C7-A72F-50D4AF95450D"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t release:rollback",
  input: "none",
  keyEquivalent: "^@M",
  name: "Release Rollback",
  output: "showAsHTML",
  uuid: "AFC4DAFC-92ED-467D-89F1-F4ECFD784C4F"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t",
  input: "none",
  keyEquivalent: "^@M",
  name: "Run Arbitrary Task …",
  output: "showAsHTML",
  uuid: "797B1987-A4CD-48D9-BE92-56351F22F6AB"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t site:site",
  input: "none",
  keyEquivalent: "^@M",
  name: "Site Generate",
  output: "showAsHTML",
  uuid: "A66DFCA3-C5F5-48F2-AB48-D0CC38436E76"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t site:run\n\nopen 'http://localhost:8080/'",
  input: "none",
  keyEquivalent: "^@M",
  name: "Site Run",
  output: "showAsHTML",
  uuid: "E7AF434A-F2F7-431B-B796-403C35E2EBDF"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t test",
  input: "none",
  keyEquivalent: "^@M",
  name: "Test",
  output: "showAsHTML",
  uuid: "C72F43DD-60E7-4F7C-B63B-84ADC3E1B67A"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -f \"$TM_FILENAME\"",
  input: "none",
  keyEquivalent: "^@M",
  name: "Test Current File",
  output: "showAsHTML",
  uuid: "2D3E0685-1F92-47E8-AE17-07F7B15AEDD2"},
 {autoScrollOutput: true,
  beforeRunningCommand: "nop",
  command: "mavenmate.sh -t verify",
  input: "none",
  keyEquivalent: "^@M",
  name: "Verify",
  output: "showAsHTML",
  uuid: "2FF6439B-3FB8-4502-825C-D1ED23F4D982"}]
