# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  bundleUUID: "D99E8C0C-792F-11D9-A212-000D93B3A10E",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\nhtml_header \"Mediawiki Cheat Sheet\"\nMarkdown.pl <<MARKDOWN\n## Paragraphs ##\n\n    Two line breaks\n    will signify\n    a paragraph.\n    \n    New paragraph starts\n    here.\n    \n    For a linebreak, just\n    use <br/> the html tag\n\n## Phrase Emphasis ##\n\n\t''italics''\n\t'''bold'''\n\n## Links ##\n\nExternal:\n\n\tAn [http://url.com/ example].\n\nWiki-links:\n\n\tAn [[example]] wikilink, possibly even\n\tfrom another namespace: [[talk:example]].\n\tRenaming [[hyperlink|links]] is easy.\n\nCategories:  add the page to a category as follows:\n\n    [[category:example]]\n\n## Images ##\n\nNot floated:\n\n\t[[Image:example.png]]\n\nThumbnail, with a caption, floated left, 200 pixels wide:\n\n    [[Image:example.png|left|200px|Floating!]]\n\nLink to the image, but don't show it on the page:\n\n    [[:Image:example.png|example.png]]\n\n## Headers ##\n\n\n\t== Header 2 ==\n\n\t=== Header 3 ===\n\n\t====== Header 6 ======\n\n\n## Lists ##\n\nOrdered:\n\n\t#  Foo\n\t#  Bar\n\nUnordered:\n\n\t* A list item. <br> With a line break.\n\t* Bar\n\nDefinition:\n\n    ; a term\n    : some defining\n    : and more defining\n    ; and another term : definition\n\nThey can be nested:\n\n\t* Abacus\n    ** answer\n\t* Bubbles\n\t*# bunk\n    *# bupkis\n    *#; BELITTLER : one who belittles\n\t*# burper\n\t* Cunning\n\nDefinitions, without the word they are defining, are used\nto indent talk pages:\n\n    Delete this article! [[user:spam]]\n    : No, it's great! [[user:eggs]]\n\n## Signatures ##\n\nComments should be signed:\n\n    ~~~ is my signature\n    ~~~~ is my signature with datestamp\n    ~~~~~ is just the datestamp\n\n## Use HTML for other formatting ##\n\nFor a monospaced font:\n\n    use the <tt>tt</tt> tag.\n\nTo center text:\n\n    <center>put me in the middle</center>\n\nFor a blockquote:\n\n    <blockquote>To be or not to be…</blockquote>\n\n\n## Prevent wiki formatting ##\n\n    Use the <nowiki>'''tag'' to write\n    '''about''</nowiki> mediawiki code\n    itself, or suppress rendering for\n    some other reason.\n\n## Templates ##\n\nOne page can be transcluded in another page\nby using a template:\n\n    {{templates}} go in curly braces\n\n## Horizontal Rules ##\n\nFour or more dashes:\n\n\t----\n\nMARKDOWN\nhtml_footer",
  input: "none",
  keyEquivalent: "^h",
  name: "Syntax Cheat Sheet",
  output: "showAsHTML",
  scope: "text.html.mediawiki",
  uuid: "873BDE02-80C9-44F4-910B-234EF7702D01"}]
