# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: "require_cmd moinedit\nmoinedit -c",
  input: "document",
  name: "Cancel",
  output: "showAsHTML",
  scope: "text.moinmoin",
  uuid: "395D5D13-1F9A-444C-A27E-3B98E268D9FE"},
 {beforeRunningCommand: "nop",
  command: "perl -pe 's/^(\\s*)(={1,4})([^=].*[^=])\\2$/$1$2=$3$2=/'",
  fallbackInput: "line",
  input: "selection",
  keyEquivalent: "@[",
  name: "Decrease Heading Level",
  output: "replaceSelectedText",
  scope: "text.moinmoin markup.heading",
  uuid: "FC6E6F47-45DC-4255-A6D9-704161A8069C"},
 {beforeRunningCommand: "nop",
  command: "require_cmd moinedit\nrequire_cmd mate\nmate \"$(moinedit -e)\"",
  input: "none",
  name: "Fetch Document [URL From Safari]",
  output: "discard",
  uuid: "880EE1CB-04F8-4944-946B-281BCD0B71B0"},
 {beforeRunningCommand: "nop",
  command: "perl -pe 's|_2f|/|g'",
  fallbackInput: "scope",
  input: "selection",
  keyEquivalent: "^L",
  name: "Fix MoinMoin Link",
  output: "replaceSelectedText",
  scope: "text.moinmoin markup.underline.link",
  uuid: "516D608C-4BA6-4B1D-A46B-CC6C367E2A61"},
 {beforeRunningCommand: "nop",
  command: 
   "require_cmd moinedit\n\n. \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\n\nhtml_header \"MoinMoin Bundle Help\" \"MoinMoin\"\nmoinedit | pre\nhtml_footer\n",
  input: "document",
  name: "Help",
  output: "showAsHTML",
  scope: "text.moinmoin",
  uuid: "75C7A294-C2B3-4AF9-86A0-50D4351CF35C"},
 {beforeRunningCommand: "nop",
  command: "perl -pe 's/^(\\s*)(={1,4})=(.*)=\\2$/$1$2$3$2/'",
  fallbackInput: "line",
  input: "selection",
  keyEquivalent: "@]",
  name: "Increase Heading Level",
  output: "replaceSelectedText",
  scope: "text.moinmoin markup.heading",
  uuid: "CF23FBDC-A1D2-48D6-B21F-EE93D891CE6D"},
 {beforeRunningCommand: "nop",
  command: "require_cmd moinedit\nmoinedit -p",
  input: "document",
  keyEquivalent: "^~@p",
  name: "Preview",
  output: "showAsHTML",
  scope: "text.moinmoin",
  uuid: "A06706CA-0E97-449E-8B45-142594657325"},
 {beforeRunningCommand: "nop",
  command: "require_cmd moinedit\ncat \"$(moinedit -r)\"",
  input: "document",
  keyEquivalent: "@r",
  name: "Reload Document",
  output: "replaceDocument",
  scope: "text.moinmoin",
  uuid: "05D7D0D5-C981-40CA-85D6-0539B2E9B7EA"},
 {beforeRunningCommand: "nop",
  command: "require_cmd moinedit\nmoinedit -s",
  input: "document",
  keyEquivalent: "^@p",
  name: "Save",
  output: "showAsHTML",
  scope: "text.moinmoin",
  uuid: "F0FC25A6-CC65-404E-AC7E-098ABC3682A2"}]
