# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: 
   "# Context-sensitive help lookup for MT tags.\n# For better recognition of \"mt:Foo\" tag names, add \":\" to your\n# word character list in TextMate's \"Text Editing\" preferences.\nif grep <<<${TM_CURRENT_WORD:-!} -Esqi '^mt$'\n    then echo \"You may need to add ':' to the \\\"Word Characters\\\" list in TextMate's \\\"Text Editing\\\" preferences.\"\n         exit\nfi\nif grep <<<${TM_CURRENT_WORD:-!} -Esq '[a-zA-Z0-9_]+'\n\tthen exit_show_html \"<meta http-equiv='Refresh' content='0;URL=http://www.movabletype.org/tag/$TM_CURRENT_WORD'>\"\n\telse echo \"Nothing to lookup (hint: place the caret on a tag name)\"\nfi",
  input: "none",
  keyEquivalent: "^h",
  name: "Documentation for Tag",
  output: "showAsTooltip",
  scope: "text.html.mt entity.name.tag.mt, text.html.mt variable.other.mt",
  uuid: "4D4EACBA-CF58-48FF-8CBC-0C93BC88AB11"},
 {beforeRunningCommand: "nop",
  bundleUUID: "005ECD5C-8762-4E90-8D8F-C778C91FFB66",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\nhtml_header \"Movable Type Help\" \"Movable Type\"\nMarkdown.pl <<'EOF'\n\nTemplate Preview commands\n-------------------------\n\nIn order to properly execute previews, you will need to configure TextMate or your project with the following shell variables:\n\n* `$MT_HOME` — The working directory of your local MT installation.\n* `$MT_BLOG` — The blog id of a weblog you wish to run your previews against.\n\nCustomizing your MT syntax highlighting\n---------------------------------------\n\nYou can customize the colors used to highlight MT container and variable tags. To do this, you can use these custom scopes for new color settings:\n\n* meta.tag.mt.variable.html: Scope that covers the entire variable tag block (from `<$` to `$>`).\n* meta.tag.mt.container.html: Scope that covers the entire container tag block (from `<` to `>`).\n* entity.name.tag.mt: Scope for the inner portion of a MT container tag.\n* variable.other.mt: Scope for the inner portion of a MT variable tag.\n\nA note about the syntax highlighting of variable tags. Variable tags are written as `<$MTEntryTitle$>` to be recognized properly. Movable Type allows you to omit the `$` characters, but this language bundle requires them so they are distinguishable from the container tags.\n\nHelp\n----\n\nA context-sensitive help command (`⌃H`) is available when the cursor is on a standard MT tag. It will display the online help for that tag from the Six Apart web site.\n\nAnd More!\n---------\n\nSeveral templates and snippets are also included with this bundle. The tab-triggered snippets are grouped by keyword (“entry”, “blog”, “category”, “archive”, etc.).\n\nAuthor\n------\n\nThis bundle is maintained by [Brad Choate][1]. Brad works at [Six Apart][2], the company that publishes [Movable Type][3]. This bundle is not officially supported by Six Apart, but you're welcome to [contact Brad][4] if you have questions or feedback regarding it.\n\n[1]: http://bradchoate.com/\n[2]: http://www.sixapart.com/\n[3]: http://www.movabletype.org/\n[4]: mailto:brad@bradchoate.com?subject=Movable%20Type%20TextMate%20Bundle\n\nEOF\nhtml_footer",
  input: "none",
  name: "Help",
  output: "showAsHTML",
  scope: "text.html.mt",
  uuid: "0122D7D0-A9D5-4FDC-95BA-BD61E52C2BAF"},
 {beforeRunningCommand: "nop",
  command: "\"$TM_BUNDLE_SUPPORT/mt-tmpl-preview.pl\" -a=c",
  input: "none",
  keyEquivalent: "^~p",
  name: "Preview Category Archive",
  output: "showAsHTML",
  scope: "text.html.mt",
  uuid: "7844998B-4EF4-4385-A3B1-55B1942BFE5A"},
 {beforeRunningCommand: "nop",
  command: "\"$TM_BUNDLE_SUPPORT/mt-tmpl-preview.pl\" -a=d",
  input: "document",
  keyEquivalent: "^~p",
  name: "Preview Daily Archive",
  output: "showAsHTML",
  scope: "text.html.mt",
  uuid: "59B2BA17-0CA5-47B6-9915-FD962855F639"},
 {beforeRunningCommand: "nop",
  command: "\"$TM_BUNDLE_SUPPORT/mt-tmpl-preview.pl\"",
  input: "document",
  keyEquivalent: "^~p",
  name: "Preview Index",
  output: "showAsHTML",
  scope: "text.html.mt",
  uuid: "1861B166-5B47-4E0D-847C-A466F5C11AEF"},
 {beforeRunningCommand: "nop",
  command: "\"$TM_BUNDLE_SUPPORT/mt-tmpl-preview.pl\" -a=i",
  input: "document",
  keyEquivalent: "^~p",
  name: "Preview Individual Archive",
  output: "showAsHTML",
  scope: "text.html.mt",
  uuid: "04B7A867-D52A-4964-AD32-C8E4F67F2F1A"},
 {beforeRunningCommand: "nop",
  command: "\"$TM_BUNDLE_SUPPORT/mt-tmpl-preview.pl\" -a=m",
  input: "document",
  keyEquivalent: "^~p",
  name: "Preview Monthly Archive",
  output: "showAsHTML",
  scope: "text.html.mt",
  uuid: "882B5FB7-D233-4D92-80C3-2D00D55CAB29"},
 {beforeRunningCommand: "nop",
  command: "\"$TM_BUNDLE_SUPPORT/mt-tmpl-preview.pl\" -a=w",
  input: "document",
  keyEquivalent: "^~p",
  name: "Preview Weekly Archive",
  output: "showAsHTML",
  scope: "text.html.mt",
  uuid: "4DB424EF-67FD-42A7-B27A-4705EAE1C5A4"}]
