# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: 
   "perl \"$TM_BUNDLE_SUPPORT/t2ol.pl\"\n\n# Yes, this actually validates as HTML 4.01 Transitional. It is surprisingly annoying to get a nested list to validate. ",
  input: "selection",
  keyEquivalent: "^@o",
  name: "Tabs to HTML OL",
  output: "replaceSelectedText",
  uuid: "4BBD1C32-8316-11D9-968E-000D9332809C"},
 {beforeRunningCommand: "nop",
  command: 
   "perl \"$TM_BUNDLE_SUPPORT/t2h.pl\"\n\n# Yes, this actually validates as HTML 4.01 Transitional. It is surprisingly annoying to get a nested list to validate. ",
  input: "selection",
  keyEquivalent: "^@o",
  name: "Tabs to HTML UL",
  output: "replaceSelectedText",
  uuid: "4B6A441D-8307-11D9-A10F-000D9332809C"},
 {beforeRunningCommand: "nop",
  command: "perl -pe '/^(\\t*)/;$a=\"*\" x (length($1)+1);s/^(\\t*)/$a /;'",
  input: "selection",
  keyEquivalent: "^@o",
  name: "Tabs to Kwiki",
  output: "replaceSelectedText",
  uuid: "E45D5856-8305-11D9-8AD4-000D9332809C"},
 {beforeRunningCommand: "nop",
  command: "perl -pe 's/^(\\t*)/$1* /;'",
  input: "selection",
  keyEquivalent: "^@o",
  name: "Tabs to Markdown",
  output: "replaceSelectedText",
  uuid: "3AE7D1AD-8300-11D9-B216-000D9332809C"},
 {beforeRunningCommand: "nop",
  command: "perl \"$TM_BUNDLE_SUPPORT/t2o.pl\"",
  input: "selection",
  keyEquivalent: "^@o",
  name: "Tabs to OPML",
  output: "openAsNewDocument",
  uuid: "DC7A2CCA-8301-11D9-9E93-000D9332809C"},
 {beforeRunningCommand: "nop",
  command: 
   "# Change the application name if you are using OmniOutliner or another program. You can edit this command or go to Prefs/Advanced/ShellVariables and set TM_OPML_APPLICATION to the name of your favorite program.\n\nif [ -z $TM_OPML_APPLICATION ] ; then\n\tTM_OPML_APPLICATION=\"OmniOutliner\"\nfi\n\nperl \"$TM_BUNDLE_SUPPORT/t2o.pl\" > /tmp/tm2oo.opml\n\nopen -a \"$TM_OPML_APPLICATION\" /tmp/tm2oo.opml ||\techo \"$TM_OPML_APPLICATION can't be found. Edit the command and replace TM_OPML_APPLICATION with an existing application.\"\n",
  input: "selection",
  keyEquivalent: "^@o",
  name: "Tabs to OmniOutliner",
  output: "showAsTooltip",
  uuid: "DBF2B50A-8303-11D9-8C1E-000D9332809C"},
 {beforeRunningCommand: "nop",
  command: "cat \"$TM_BUNDLE_PATH/README.html\"",
  input: "selection",
  keyEquivalent: "^@o",
  name: "View Outlines README",
  output: "showAsHTML",
  uuid: "F60652D5-8316-11D9-8D63-000D9332809C"}]
