# Encoding: UTF-8

[{beforeRunningCommand: "saveActiveFile",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\"",
  input: "none",
  keyEquivalent: "~@",
  name: "Alternate File",
  output: "showAsTooltip",
  scope: 
   "source.ruby.rails, text.html.ruby, source.ruby.rails.embedded.html, source.yaml, text.haml, source.css, source.js, source.sass",
  uuid: "0CCC8443-40F3-4BAB-9440-D737562B5F45"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/fixture_auto_complete.rb\" ",
  fallbackInput: "line",
  input: "selection",
  keyEquivalent: "~",
  name: "Autocomplete Foreign Key Fixture Reference",
  output: "insertAsSnippet",
  scope: "source.yaml, meta.rails.unit_test, meta.rails.functional_test",
  uuid: "0BCF0EE2-35EE-4959-A771-E74D55271D5A"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" \"${TM_BUNDLE_SUPPORT}/bin/fixture_auto_complete.rb\" preserve",
  fallbackInput: "line",
  input: "selection",
  keyEquivalent: "~$",
  name: "Autocomplete Foreign Key Fixture Reference (habtm)",
  output: "insertAsSnippet",
  scope: "source.yaml",
  uuid: "275C0B86-F735-49B6-8A22-218A8F4CC2E0"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/generate.rb\" &>/dev/null &\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Call Generate Script",
  output: "discard",
  scope: "source.ruby.rails, source.yaml",
  uuid: "4904EDC7-5ED3-4132-AAB2-C2AD87C97EFE"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:test:clone\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Clone Development DB to Test DB",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "6F2AB859-46E3-4FF5-A9A7-E9A813AB5DE1"},
 {beforeRunningCommand: "saveModifiedFiles",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/create_partial_from_selection.rb\"\n",
  fallbackInput: "line",
  input: "selection",
  keyEquivalent: "^H",
  name: "Create Partial From Selection",
  output: "replaceSelectedText",
  scope: "source.ruby.rails, text.html.ruby, text.haml",
  uuid: "1DD8A214-1C97-45BA-ADEE-8F888DDE8570"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:schema:dump\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Dump DB to schema.rb",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "310C901C-EF32-4E88-938A-804ABBF8C428"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_file_on_current_line.rb\"",
  input: "none",
  keyEquivalent: "~@",
  name: "File on Current Line",
  output: "showAsTooltip",
  scope: 
   "source.ruby.rails, text.html.ruby, source.ruby.rails.embedded.html, text.haml",
  uuid: "09BB96F2-75FD-48A7-8314-B5B56B09B477"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" controller",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Controller",
  output: "showAsTooltip",
  scope: 
   "text.html.ruby, source.ruby.rails.embedded.html, meta.rails.helper, meta.rails.functional_test, source.js, source.css, source.yaml, meta.rails.model, meta.rails.unit_test, text.haml",
  uuid: "9453F0B3-B946-445F-BDB0-B01DE70732FC"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" fixture",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Fixture",
  output: "showAsTooltip",
  scope: 
   "meta.rails.controller, meta.rails.helper, meta.rails.model, meta.rails.unit_test, meta.rails.functional_test",
  uuid: "638D94A4-BDFC-4FE9-8909-9934F3FD2899"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" functional_test",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Functional Test",
  output: "showAsTooltip",
  scope: 
   "meta.rails.controller, meta.rails.helper, meta.rails.model, source.yaml, meta.rails.unit_test",
  uuid: "DFE393BE-0764-49FE-B464-6350A50921E6"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" helper",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Helper",
  output: "showAsTooltip",
  scope: 
   "text.html.ruby, source.ruby.rails.embedded.html, meta.rails.controller, meta.rails.model, meta.rails.unit_test, meta.rails.functional_test, text.haml",
  uuid: "51C9C27A-D931-49F9-B6D8-C0E7ABEC992D"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" javascript",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Javascript",
  output: "showAsTooltip",
  scope: 
   "text.html.ruby, source.ruby.rails.embedded.html, meta.rails.controller, meta.rails.helper, text.haml",
  uuid: "B078346F-61D8-4E75-9427-80720FBC67F7"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" model",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Model",
  output: "showAsTooltip",
  scope: 
   "text.html.ruby, source.ruby.rails.embedded.html, meta.rails.helper, meta.rails.unit_test, source.js, source.css, source.yaml, meta.rails.controller, meta.rails.functional_test, text.haml",
  uuid: "C7151BF3-7068-4344-9B09-86F3BF4A9C63"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" stylesheet",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Stylesheet",
  output: "showAsTooltip",
  scope: 
   "text.html.ruby, source.ruby.rails.embedded.html, meta.rails.controller, meta.rails.helper, text.haml",
  uuid: "B207BBD4-D6AA-41E9-9530-27210F2D7B66"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" unit_test",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to Unit Test",
  output: "showAsTooltip",
  scope: 
   "meta.rails.controller, meta.rails.helper, meta.rails.model, meta.rails.functional_test, source.yaml",
  uuid: "BDBB15A4-2824-4BEC-93A5-7475F9C46A39"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/go_to_alternate_file.rb\" view",
  input: "none",
  keyEquivalent: "~$@",
  name: "Go to View",
  output: "showAsTooltip",
  scope: "meta.rails.controller, meta.rails.mailer, source.js, source.css",
  uuid: "EE862691-A624-4797-90CF-EDD39EFB2D8E"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/list_plugins.rb\"",
  input: "none",
  keyEquivalent: "^|",
  name: "Install Plugin",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "46ECE243-0448-4A64-A223-27CC21E7704D"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:fixtures:load\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Load Fixtures (Development DB)",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "5EEA0C71-B34B-4408-953B-F47AAD343CCC"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:fixtures:load -v RAILS_ENV -a test\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Load Fixtures (Test DB)",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "F758BFD1-00CA-4742-BE71-032580080F5C"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:schema:load\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Load schema.rb to DB",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "6DEF923E-2347-46EC-AFBE-183D08E63DC1"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:migrate\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Migrate to Current",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "985F56D4-82ED-4C45-8250-2ECCFC71957E"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\n# Find the previous version number from the schema.rb file\nexport PREVIOUS=`grep 'Schema\\.define' \"$TM_PROJECT_DIRECTORY/db/schema.rb\" | ruby -e 'print $stdin.read.scan(/\\d+/).first.to_i - 1'`\n\n# Migrate database to the previous version\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:migrate -v VERSION -a $PREVIOUS\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Migrate to Previous Version",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "9A1AE6BA-8350-4AB7-B5BD-969A7E64CF29"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\n# Find the current version number from the schema.rb file\nexport CURRENT=`grep 'Schema\\.define' \"$TM_PROJECT_DIRECTORY/db/schema.rb\" | ruby -e 'print $stdin.read.scan(/\\d+/).first'`\n\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:migrate -q \"Migrate to which version? (Current version: $CURRENT)\" -v VERSION\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Migrate to Version ...",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "07C696F8-79F5-4E0B-9EE9-03B693A54ABB"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/generate_quick_migration.rb\"",
  fallbackInput: "word",
  input: "none",
  keyEquivalent: "^M",
  name: "Quick Migration",
  output: "discard",
  scope: "source.ruby.rails, source.yaml, text.html.ruby",
  uuid: "D696FA2C-785A-4B73-A2F6-F750904DD7C2"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" db:migrate:redo\n",
  input: "none",
  keyEquivalent: "^|",
  name: "Redo Last Migration",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "CFDA9F62-D071-4E0F-AD10-66AE0729FFCF"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/show_schema.rb\"\n",
  input: "none",
  keyEquivalent: "^@S",
  name: "Show DB Schema for Current Class",
  output: "showAsTooltip",
  scope: "source.ruby.rails",
  uuid: "1970AE74-3949-40B3-B263-727AA3FF167A"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" test",
  input: "none",
  keyEquivalent: "^\\",
  name: "Test All",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "DC549A45-D9B0-11DC-94E9-00112475D960"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" test:functionals",
  input: "none",
  keyEquivalent: "^\\",
  name: "Test Functionals",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "F4EA552D-D9B0-11DC-94E9-00112475D960"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" test:integration",
  input: "none",
  keyEquivalent: "^\\",
  name: "Test Integration",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "04A30A4D-D9B1-11DC-94E9-00112475D960"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" test:plugins",
  input: "none",
  keyEquivalent: "^\\",
  name: "Test Plugins",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "0D966168-D9B1-11DC-94E9-00112475D960"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" test:recent",
  input: "none",
  keyEquivalent: "^\\",
  name: "Test Recent",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "190401C2-D9B1-11DC-94E9-00112475D960"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" test:uncommitted",
  input: "none",
  keyEquivalent: "^\\",
  name: "Test Uncommitted",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "212C3047-D9B1-11DC-94E9-00112475D960"},
 {beforeRunningCommand: "nop",
  command: 
   "RUBYLIB=\"$TM_BUNDLE_SUPPORT/lib:$RUBYLIB\"\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/bin/rake_helper.rb\" test:units",
  input: "none",
  keyEquivalent: "^\\",
  name: "Test Units",
  output: "showAsHTML",
  scope: "source.ruby.rails, source.yaml",
  uuid: "2C60CBA1-D9B1-11DC-94E9-00112475D960"},
 {beforeRunningCommand: "nop",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\nhtml_header \"Ruby on Rails Bundle Help\" \"Ruby on Rails\"\ncat \"$TM_BUNDLE_SUPPORT/../website/demo.html\"\nhtml_footer\n\n",
  input: "none",
  keyEquivalent: "^h",
  name: "View demo help",
  output: "showAsHTML",
  scope: "source.ruby.rails",
  uuid: "964436B8-E578-11DC-8177-00112475D960"}]
