# Encoding: UTF-8

[{beforeRunningCommand: "nop",
  command: 
   "require_cmd \"${TM_SVK:=svk}\" \"If you have installed svk, then you need to either update your <tt>PATH</tt> or set the <tt>TM_SVK</tt> shell variable (e.g. in Preferences / Advanced)\"\n\n\"${TM_RUBY:=ruby}\" -r \"$TM_SUPPORT_PATH/lib/shelltokenize.rb\" <<END\n\tsvk = ENV['TM_SVK'] || \"svk\"\n\tputs %x{\#{svk} add \#{TextMate.selected_paths_for_shell}}\nEND",
  input: "none",
  keyEquivalent: "^~A",
  name: "Add to Repository",
  output: "showAsTooltip",
  uuid: "F41366B2-C373-11D9-8A81-000A95BCAFA8"},
 {beforeRunningCommand: "nop",
  command: 
   "require_cmd \"${TM_SVK:=svk}\" \"If you have installed svk, then you need to either update your <tt>PATH</tt> or set the <tt>TM_SVK</tt> shell variable (e.g. in Preferences / Advanced)\"\n\n\"${TM_SVK:=svk}\" blame \"$TM_FILEPATH\" \\\n2>&1| \"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/format_blame.rb\"",
  input: "none",
  keyEquivalent: "^~A",
  name: "Blame",
  output: "showAsHTML",
  uuid: "B37F2E1A-C35F-11D9-AB2C-000A95BCAFA8"},
 {beforeRunningCommand: "saveModifiedFiles",
  command: 
   "require_cmd \"${TM_SVK:=svk}\" \"If you have installed svk, then you need to either update your <tt>PATH</tt> or set the <tt>TM_SVK</tt> shell variable (e.g. in Preferences / Advanced)\"\n\nCommitWindow=\"$TM_SUPPORT_PATH/bin/CommitWindow.app/Contents/MacOS/CommitWindow\"\nexport CommitWindow\n\nTM_SVK=\"${TM_SVK:=svk}\"\nexport TM_SVK\n\n\"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/svk_commit.rb\"\n",
  input: "none",
  keyEquivalent: "^~A",
  name: "Commit",
  output: "showAsHTML",
  uuid: "C03C7374-C371-11D9-AAA6-000A95BCAFA8"},
 {beforeRunningCommand: "nop",
  command: 
   "TMPFILE=`mktemp /tmp/tm-svk.XXXXXX` || exit 1\n\nmv \"$TMPFILE\" \"$TMPFILE.diff\"\nTMPFILE=\"$TMPFILE.diff\"\n\n# -rBASE is the same as specifying no revision -- it's the version that you have checked out.\n\"${TM_SVK:=svk}\" diff -rBASE \"$TM_FILEPATH\" &> \"$TMPFILE\"\n\nopen -a TextMate \"$TMPFILE\" &\n\n#rm \"$TMPFILE\" # ideally, we'd do this, but it creates a race condition, because 'open' is asynchronous.\n",
  input: "none",
  keyEquivalent: "^~A",
  name: "Diff With Working Copy (BASE)",
  output: "discard",
  uuid: "0987069A-C370-11D9-AAA6-000A95BCAFA8"},
 {beforeRunningCommand: "nop",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\nhtml_header \"SVK Bundle Help\" \"SVK\"\n\"$TM_SUPPORT_PATH/lib/markdown_to_help.rb\" <<'EOF'\n\nThis README just documents what the commands of this Bundle do and how you can <a href=\"#sect_2\">fine-tune</a> their behaviour; if you need general SVK Help/Introduction, you should look at the <a href=\"http://svk.elixus.org/\">SVK homepage</a>.\n      \n# Commands\n         \n-   **Add to Repository**\n\n    __Target__:  selected project files/folders or the active file if it doesn't belong to a project\n    \n    Adds the targets to the repository.\n\n-   **Blame**\n\n    __Target__:  active file\n        \n    Displays a line-by-line history of the file, showing you who wrote which line in what revision.  Click a line to jump to it in an editor window.  Hover over a revision number or author name to see when the corresponding line was last changed. The date format is <a href=\"#sect_2\">adjustable</a> with `TM_SVK_DATE_FORMAT`.\n    \n    \"wc\" means the last change was in your working copy.\n\n-   **Commit**\n\n    __Target__:  selected project files/folders or the active file if it doesn't belong to a project\n    \n    Commits your changed files to the repository. A dialog asks you for the description of your changes; you may also choose to exclude files from the commit by un-checking them. If no files are selected or active, this command does nothing. If the target files have no local changes, nothing happens.\n    \n-   **Diff With Working Copy (BASE)**\n    \n    __Target__:  active file\n    \n    Displays the differences between the active file and an unaltered, pristine copy of the file at the same revision.\n    \n    Equivalent to `svk diff -rBASE`\n        \n-   **Info**\n\n    __Target__:  selected project files/folders or the active file if it doesn't belong to a project\n\n    Displays detailed information about the selected files. Some parameters are configurable via shell variables; see the <a href=\"#sect_2\">Configuration Options</a> section below.\n    \n-   **Log**\n\n    __Target__:  selected project files/folders or the active file if it doesn't belong to a project\n    \n    Displays the commit message history for the selected files. Some parameters are configurable via shell variables; see the <a href=\"#sect_2\">Configuration Options</a> section below.  (TODO: if multiple files are selected, only the logs from the first are shown.)\n\n-   **Revert**\n\n    __Target__:  active file\n    \n    Revert changes made in checkout copies.\n\n-   **Status**\n\n    __Target__:  directory of active file\n    \n    Displays a list of files with changes in your working copy, along with the type of change for each file.\n\n-   **Update to Newest**\n\n    __Target__:  selected project files/folders or the active file if it doesn't belong to a project\n    \n    Updates the targets with the newest changes from the repository.\n\n\n# Configuration Options\n         \nThese [static variables](?static_variables) allow you to tweak the behaviour of the certain commands if need be. The default values should make sense for normal use.\n         \n-   `TM_SVK`\n\n    __Default__: `svk`\n    \n    The path to your svk executable.\n            \n-   `TM_RUBY`\n\n    __Default__: `ruby`\n    \n    Here you can tweak with what Ruby the formatting scripts will be executed.\n            \n-   `TM_SVK_DATE_FORMAT`\n\n    __Default__: *not set* (No Changes, just show what SVK shows)\n                  \n    A date format string that allows you to tweak the format in which Blame, Log and Info show you dates.  See <a title=\"Manual Page For strftime(3)\" href=\"http://developer.apple.com/documentation/Darwin/Reference/ManPages/man3/strftime.3.html\">strftime(3)</a> for what you can enter here.\n            \n-   `TM_SVK_CLOSE`\n\n    __Default__: `false`\n    \n\tWith this option you can adjust whether the windows of Blame and Info close if you click on a link which opens a file in TM.  Set it to `1` or `true` if windows should close or to something else if they should not.\n            \n-   `TM_SVK_LOG_RANGE`\n\n    __Default__: `BASE:1`\n\n    The default range to query for log messages.\n            \n-   `TM_SVK_LOG_LIMIT`\n\n    __Default__: `9`\n\n    The number of messages to show. `0` means no limit.\n            \n-   `TM_SVK_INFO_HIDE`\n\n    __Default__: *not set* (nothing)\n    \n    Here you can adjust what keys of the info stream you don't want to see, it is case insensitive and a comma (`,`) separated list.  If you enter a `*`, it is assumed that you want to hide all vars, if so, you can make some values visible again with `TM_SVK_INFO_SHOW`.\n            \n-   `TM_SVK_INFO_SHOW`\n\n    __Default__: *not set* (everything else)\n    \n    This is also a comma-separated list of keys, it just makes sense if you did hide all with the above var. `*` has no special meaning here. Everything you enter here will be shown if you want to hide everything else.\n\n\n# Authors\n         \n- <a href=\"mailto:glasser@mit.edu\">David Glasser</a>, ported to SVK from Subversion\n- Chris Thomas (Subversion bundle) (Idea, Status, Diffs, Commit, Add, and Updates)\n- Torsten Becker (Subversion bundle) (Blame, Log, Info, and Revert)\n\nEOF\nhtml_footer\n",
  dontFollowNewOutput: 1,
  input: "none",
  keyEquivalent: "^~A",
  name: "Help",
  output: "showAsHTML",
  uuid: "5263FCE3-C32A-11D9-BFEF-000A95BCAFA8"},
 {beforeRunningCommand: "nop",
  command: 
   "TM_SVK=\"${TM_SVK:=svk}\"\nTM_RUBY=\"${TM_RUBY:=ruby}\"\nFORMAT_INFO=\"${TM_BUNDLE_SUPPORT}/format_info.rb\"\n\nif [[ -z $TM_SELECTED_FILES ]]; then\n   \"$TM_SVK\" info \"$TM_FILEPATH\" \\\n   2>&1| \"$TM_RUBY\" -- \"$FORMAT_INFO\"\nelse\n   eval \"$TM_SVK\" info $TM_SELECTED_FILES \\\n   2>&1| \"$TM_RUBY\" -- \"$FORMAT_INFO\"\nfi",
  input: "none",
  keyEquivalent: "^~A",
  name: "Info",
  output: "showAsHTML",
  uuid: "70BCF12B-C35D-11D9-AB2C-000A95BCAFA8"},
 {beforeRunningCommand: "nop",
  command: 
   "# XXX: svk log doesn't support multiple paths\n#      so if multiple files are selected, it will\n#      only do the first one!\n\nTM_SVK=\"${TM_SVK:=svk}\"\nTM_RUBY=\"${TM_RUBY:=ruby}\"\nFORMAT_LOG=\"${TM_BUNDLE_SUPPORT}/format_log.rb\"\nTM_SVK_LOG_RANGE=\"${TM_SVK_LOG_RANGE:=BASE:1}\"\n\nif [[ -z $TM_SELECTED_FILES ]]; then\n   \"$TM_SVK\" log -vr\"$TM_SVK_LOG_RANGE\" \"$TM_FILEPATH\" \\\n   2>&1| \"$TM_RUBY\" -- \"$FORMAT_LOG\"\nelse\n   eval \"$TM_SVK\" log -vr\"$TM_SVK_LOG_RANGE\" $TM_SELECTED_FILES \\\n   2>&1| \"$TM_RUBY\" -- \"$FORMAT_LOG\"\nfi",
  input: "none",
  keyEquivalent: "^~A",
  name: "Log",
  output: "showAsHTML",
  uuid: "9BF6E13C-C31A-11D9-820C-000A95BCAFA8"},
 {beforeRunningCommand: "nop",
  command: 
   "require_cmd \"${TM_SVK:=svk}\" \"If you have installed svk, then you need to either update your <tt>PATH</tt> or set the <tt>TM_SVK</tt> shell variable (e.g. in Preferences / Advanced)\"\n\nif [[ -z $TM_SELECTED_FILES ]]\n\tthen\n\tTM_SELECTED_FILES=\"'$TM_FILEPATH'\"\nfi\n\"$TM_BUNDLE_SUPPORT/revert_file.rb\" $TM_SELECTED_FILES\n",
  input: "none",
  keyEquivalent: "^~A",
  name: "Revert",
  output: "showAsTooltip",
  uuid: "8FCB4C8F-23CD-4D2E-A9F2-C4564DFFEB2A"},
 {beforeRunningCommand: "nop",
  command: 
   "export WorkPath=\"$TM_DIRECTORY\"\n\n# show it..\n\"${TM_SVK:=svk}\" status \"$WorkPath\" 2>&1| \"${TM_RUBY:=ruby}\" -- \"${TM_BUNDLE_SUPPORT}/format_status.rb\"\n",
  input: "none",
  keyEquivalent: "^~A",
  name: "Status",
  output: "showAsHTML",
  uuid: "C17472A0-C36B-11D9-954B-000A95BCAFA8"},
 {beforeRunningCommand: "saveModifiedFiles",
  command: 
   "\"${TM_RUBY:=ruby}\" -r \"$TM_SUPPORT_PATH/lib/shelltokenize.rb\" <<END\n\tsvk = ENV['TM_SVK'] || \"svk\"\n\tputs %x{\#{svk} update \#{TextMate.selected_paths_for_shell}}\nEND\n",
  input: "none",
  keyEquivalent: "^~A",
  name: "Update to Newest",
  output: "showAsTooltip",
  uuid: "D79E0650-C374-11D9-8A81-000A95BCAFA8"}]
