# Encoding: UTF-8

[{beforeRunningCommand: "saveActiveFile",
  command: "txt2tags \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "@r",
  name: "Convert to Default Target",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "0EC28386-027E-49E4-AEDE-B212796B5AD8"},
 {beforeRunningCommand: "saveActiveFile",
  command: 
   "HTML_FILE_PATH=$(txt2tags -t html \"$TM_FILEPATH\" | sed -n 's/^txt2tags wrote //p')\ntest -z \"$HTML_FILE_PATH\" || open \"$HTML_FILE_PATH\"",
  input: "none",
  keyEquivalent: "^@p",
  name: "Convert to HTML and Preview in Browser",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "8EC9DC0F-5F86-4258-AC0B-304D90E1E126"},
 {beforeRunningCommand: "nop",
  command: 
   "if test -z \"$TM_SELECTED_TEXT\"; then\n\techo\n\techo \": Term 1\"\n\techo \"Description 1\"\n\techo \": Term 2\"\n\techo \"Description 2\"\n\techo \":\"\nelse\n\techo \"$TM_SELECTED_TEXT\" | sed 's/^/: /'\nfi",
  fallbackInput: "none",
  input: "selection",
  name: "Definition List",
  output: "replaceSelectedText",
  scope: "text.txt2tags",
  tabTrigger: ":",
  uuid: "CE8367B5-2C5D-4057-B1EE-9EB026173E31"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t doku \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "DokuWiki",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "87C7E27B-D787-48D3-A3B0-5D623264263E"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t gwiki \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "Google Code Wiki",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "4C1A60D8-747B-4C2B-BFC9-ABC0EE33DE24"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t html \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "HTML",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "05B145C3-6D67-4E63-8163-FE161E9CA4EB"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t tex \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "LaTeX",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "505FE1E0-237F-460F-B9E7-9F05A9B7E85C"},
 {beforeRunningCommand: "nop",
  command: 
   "if test -z \"$TM_SELECTED_TEXT\"; then\n\techo\t\n\techo \"- Item 1\"\n\techo \"- Item 2\"\n\techo \"-\"\nelse\n\techo \"$TM_SELECTED_TEXT\" | sed 's/^/- /'\nfi",
  fallbackInput: "none",
  input: "selection",
  name: "List",
  output: "replaceSelectedText",
  scope: "text.txt2tags",
  tabTrigger: "-",
  uuid: "5928BD4D-E6E6-49F3-ADFE-518FC4E663A7"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t lout \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "Lout",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "CAB527E2-384C-46CE-96E0-641F941C9776"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t mgp \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "MagicPoint (mgp)",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "ED33B096-631A-41B2-AEB0-50E771F41E37"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t man \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "Man Page",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "90B93795-AC8C-41C1-8C41-786C1A113D43"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t moin \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "MoinMoin (wiki)",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "E03416E2-4742-4AC4-B152-D838A6542696"},
 {beforeRunningCommand: "nop",
  command: 
   "if test -z \"$TM_SELECTED_TEXT\"; then\n\techo\n\techo \"+ Item 1\"\n\techo \"+ Item 2\"\n\techo \"+\"\nelse\n\techo \"$TM_SELECTED_TEXT\" | sed 's/^/+ /'\nfi",
  fallbackInput: "none",
  input: "selection",
  name: "Numbered List",
  output: "replaceSelectedText",
  scope: "text.txt2tags",
  tabTrigger: "+",
  uuid: "70E9A4C5-9F6F-4139-BE41-3685017D6169"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t pm6 \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "PageMaker",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "0E94ACC5-07FC-48BA-8FE0-9557224856F8"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t txt \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "Plain Text",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "1B1B0B59-A69B-4601-9884-23480A27914B"},
 {beforeRunningCommand: "nop",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\n\nhtml_header \"Txt2tags Preview\"\ntxt2tags -t html -i- -o- |\n\tsed \"s|<HEAD>|&<base href='tm-file://${TM_FILEPATH// /%20}'>|\"\n\t# ^needed for images, CSS files and friends\nhtml_footer\n",
  input: "document",
  keyEquivalent: "^~@p",
  name: "Preview",
  output: "showAsHTML",
  scope: "text.txt2tags",
  uuid: "4B8C62A1-82C3-40C6-9595-4546EE8B2CA0"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t sgml \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "Sgml",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "AFAA4B88-20AB-44B3-8BF3-4D3E66FEB3A0"},
 {beforeRunningCommand: "nop",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\n\ntest -z $TM_FILENAME && title=\"Txt2tags\" || title=\"${TM_FILENAME%.*}\"\n\nhtml_header \"$title - Active Configuration\"\n\ncd \"$TM_DIRECTORY\" # needed to expand possible includes\ntxt2tags -t txt --dump-config -i- -o- | pre\n\nhtml_footer",
  input: "document",
  name: "Show Active Configuration",
  output: "showAsHTML",
  scope: "text.txt2tags",
  uuid: "69189D22-7020-4A1D-AF4C-1A3A068D0ADA"},
 {beforeRunningCommand: "nop",
  command: 
   ". \"$TM_SUPPORT_PATH/lib/webpreview.sh\"\n\ntest -z $TM_FILENAME && title=\"Txt2tags\" || title=\"${TM_FILENAME%.*}\"\n\nhtml_header \"$title - Document Outline\"\n\ncd \"$TM_DIRECTORY\" # needed to expand possible includes\ntxt2tags -t txt --toc-level 5 --toc-only -i- -o- | pre\n\nhtml_footer",
  input: "document",
  name: "Show Document Outline",
  output: "showAsHTML",
  scope: "text.txt2tags",
  uuid: "423F0F96-A0B8-4643-B8E1-A55157FC53E4"},
 {beforeRunningCommand: "nop",
  command: 
   "cat <<\"TEXT\"\n⌘B\t\tBold\n⌘I\t\tItalic\n⌘U\t\tUnderline\n⌘K\t\tMonospaced\n⌥⌘K\tVerbatim Block (code)\n⌃⇧L\tLink\n⌃⇧I\tImage\n⌃⇧|\tTable\n⌃⇧+\tNumbered Title\n⌃=\t\tTitle\n⌘]\t\tQuote (In)\n⌘[\t\tQuote (Out)\n⌘/\t\tComment Lines (On/Off)\nTEXT\n",
  input: "none",
  keyEquivalent: "@",
  name: "Show Keyboard Shortcuts",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "7C1AFFF2-BA6F-4AB7-AE1A-D60D737BBB14"},
 {beforeRunningCommand: "nop",
  command: "txt2tags --version | sed 's/<.*//'",
  input: "none",
  name: "Show Txt2tags Version",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "BF01B32B-534E-4886-AA99-69B4C9676BA3"},
 {beforeRunningCommand: "nop",
  command: "open http://txt2tags.sourceforge.net/markup.html",
  input: "none",
  keyEquivalent: "^h",
  name: "Syntax Cheat Sheet",
  output: "discard",
  scope: "text.txt2tags",
  uuid: "B44403DA-5B16-407D-9750-8F2805B84FD6"},
 {beforeRunningCommand: "nop",
  command: 
   "if test -z \"$TM_SELECTED_TEXT\"; then\n\techo\t\n\techo \"|| Heading1 | Heading 2 | Heading 3 |\"\n\techo \"| left      |   center  |     right |\"\n\techo\nelse\n\ttab=$(echo -ne \\\\t)\n\techo \"$TM_SELECTED_TEXT\" |\n\t\tsed \"s/$tab/ | /g;s/.*/| & |/\"\nfi",
  fallbackInput: "none",
  input: "selection",
  keyEquivalent: "^|",
  name: "Table",
  output: "replaceSelectedText",
  scope: "text.txt2tags",
  tabTrigger: "|",
  uuid: "3B5D493F-111A-4639-BA28-B2119770504B"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t wiki \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "Wikipedia",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "3D1E0C6B-23DD-44E1-A2F0-2F143AE9D898"},
 {beforeRunningCommand: "saveActiveFile",
  command: "txt2tags -t xhtml \"$TM_FILEPATH\"",
  input: "none",
  keyEquivalent: "^H",
  name: "XHTML",
  output: "showAsTooltip",
  scope: "text.txt2tags",
  uuid: "C95007FC-50A3-4BBC-AACF-3EF6EE2AA7F5"}]
