# Encoding: UTF-8

[{content: 
   "${1:set the_application to }choose application with prompt \"${2:Choose an application:}\"${3: ¬\n\twith multiple selections allowed}\n$0",
  name: "Application(s)",
  scope: "source.applescript",
  tabTrigger: "choose",
  uuid: "61FA9A41-E511-488F-AA30-4216C9154BE7"},
 {content: 
   "${1:set the_color to }choose color default color ${2:{65536, 65536, 65536\\}}\n$0",
  name: "Color",
  scope: "source.applescript",
  tabTrigger: "choose",
  uuid: "C8B17E74-0D0F-4FC9-B53C-B2CD2BBE4EA4"},
 {content: 
   "${1:set the_file to }choose file with prompt \"${2:Pick a file:}\"${3: ¬\n\tdefault location path to home folder}${4: ¬\n\twith invisibles}${5: ¬\n\twith multiple selections allowed}${6: ¬\n\twith showing package contents}\n$0",
  name: "File(s)",
  scope: "source.applescript",
  tabTrigger: "choose",
  uuid: "5C6AB1CA-170D-42A9-8E3C-961FE1054934"},
 {content: 
   "${1:set the_folder to }choose folder with prompt \"${2:Pick a folder:}\"${3: ¬\n\tdefault location path to home folder}${4: ¬\n\twith invisibles}${5: ¬\n\twith multiple selections allowed}${6: ¬\n\twith showing package contents}\n$0",
  name: "Folder(s)",
  scope: "source.applescript",
  tabTrigger: "choose",
  uuid: "CDEB7EDE-7171-4801-AE12-258ED3F7A2BA"},
 {content: 
   "${1:set the_filename to }choose file name with prompt \"${2:Name this file:}\" ¬\n\tdefault name \"${3:untitled}\" default location ${4:path to home folder}\n$0",
  name: "New File",
  scope: "source.applescript",
  tabTrigger: "choose",
  uuid: "DE1A37AA-FB0F-480F-99DC-3D79B35A49C1"},
 {content: 
   "display dialog \"${1:text}\" ¬\n\t${2:with icon ${3:1} ¬\n\t}buttons {\"${4:OK}\"} default button 1\n$0",
  name: "OK",
  scope: "source.applescript",
  tabTrigger: "dialog",
  uuid: "244EC5B2-5821-4364-8585-A2B241A57590"},
 {content: 
   "display dialog \"${1:text}\" ¬\n\t${2:with icon ${3:1} ¬\n\t}buttons {\"${5:Cancel}\", \"${4:OK}\"} ¬\n\tdefault button \"$4\"\nset button_pressed to button returned of result\nif button_pressed is \"$4\" then\n\t${6:-- action for default button button goes here}\nelse\n\t-- action for cancel button goes here\nend if",
  name: "OK/Cancel",
  scope: "source.applescript",
  tabTrigger: "dialog",
  uuid: "3495D4D5-E454-4A90-9288-8E7D34094544"},
 {content: 
   "display dialog \"${1:text}\" ¬\n\t${2:with icon ${3:1} ¬\n\t}buttons {\"${5:Cancel}\", \"${6:Other Choice}\", \"${4:OK}\"} ¬\n\tdefault button \"$4\"\nset button_pressed to button returned of result\nif button_pressed is \"$4\" then\n\t${7:-- action for default button button goes here}\nelse if button_pressed is \"$5\" then\n\t-- action for cancel button goes here\nelse\n\t-- action for other button goes here\nend if",
  name: "OK/Cancel/Other",
  scope: "source.applescript",
  tabTrigger: "dialog",
  uuid: "7DD1F1C1-3E7B-4157-951E-58B22BA00AB9"},
 {content: 
   "set the_result to display dialog \"${1:text}\" ¬\n\tdefault answer \"${2:type here}\" ¬\n\t${3:with icon ${4:1} ¬\n\t}buttons {\"${6:Cancel}\", \"${5:OK}\"} ¬\n\tdefault button \"$5\"\nset button_pressed to button returned of the_result\nset text_typed to text returned of the_result\nif button_pressed is \"$5\" then\n\t${7:-- action for default button button goes here}\nelse\n\t-- action for cancel button goes here\nend if",
  name: "Text Field",
  scope: "source.applescript",
  tabTrigger: "dialog",
  uuid: "E4CD6ED0-73A9-48A5-95F1-74794A93401F"},
 {content: 
   "${1:set the_url to }choose URL showing ${2:Web} servers with editable URL\n$0",
  name: "URL",
  scope: "source.applescript",
  tabTrigger: "choose",
  uuid: "5100F3C7-EC8E-43C3-B844-2F384FCEC6C4"},
 {content: "set the_choice to choose from list ${1:{\"${2:choices}\"\\}}\n$0 ",
  name: "Item From List",
  scope: "source.applescript",
  tabTrigger: "choose",
  uuid: "1D418F08-770F-4407-AE6A-3CCF2CD9FA6E"},
 {content: 
   "display alert \"${1:alert text}\" ¬\n\t${2:message \"${3:message text}\" ¬\n\t}${4:as warning}",
  name: "Display Alert",
  scope: "source.applescript",
  tabTrigger: "alert",
  uuid: "36586BF4-F77B-42B6-ADEF-AD2B65298602"},
 {content: 
   "${1:set shell_stdout to }do shell script ${3:¬\n\t\"${2:#script}\"} ¬\n\twithout altering line endings\n$0",
  name: "do shell script …",
  scope: "source.applescript",
  tabTrigger: "shell",
  uuid: "A26CF48B-F79C-4AEC-B2DC-9063DA264DDB"},
 {content: "if ${1:true} then\n\t${0:-- insert actions here}\nend if",
  name: "if … end",
  scope: "source.applescript",
  tabTrigger: "if",
  uuid: "301C492A-03BE-4EFF-87A9-2FD276376B9B"},
 {content: 
   "on ${1:functionName}(${2:arguments})\n\t${3:-- function actions}\nend $1",
  name: "on function … end",
  scope: "source.applescript",
  tabTrigger: "on",
  uuid: "AD6C0DB7-E3A9-44A0-A9AC-225BBAF49554"},
 {content: 
   "repeat ${1:${2:number} times}\n\t${0:-- insert actions here}\nend repeat",
  name: "repeat … end",
  scope: "source.applescript",
  tabTrigger: "rep",
  uuid: "4FFDA694-2B17-41AF-B92A-2172612CC82D"},
 {content: 
   "tell ${2:app \"${1:TextMate}\"}\n\t${0:-- insert actions here}\nend tell",
  name: "tell [app] … end",
  scope: "source.applescript",
  tabTrigger: "tell",
  uuid: "3E62DF03-32E3-40B6-978F-CD3DD86F8494"},
 {content: 
   "try\n\t${0:-- actions to try}\non error\n\t-- error handling\nend try",
  name: "try … on error … end",
  scope: "source.applescript",
  tabTrigger: "try",
  uuid: "A7169FD9-63FB-46EB-974F-6B31FFF4C52B"},
 {content: 
   "using terms from ${1:app \"${2:Finder}\"}\n\t${0:-- insert actions here}\nend using terms from",
  name: "using terms from [app] … end",
  scope: "source.applescript",
  tabTrigger: "terms",
  uuid: "9E5E9C0B-471D-41FE-83CF-6BC51783B27F"},
 {content: 
   "with timeout ${1:number} seconds\n\t${0:-- insert actions here}\nend timeout",
  name: "with timeout … end",
  scope: "source.applescript",
  tabTrigger: "timeout",
  uuid: "9C5B660B-94B9-44DD-AA84-F212AAE0065A"},
 {content: 
   "on UIscript_check()\n\t-- check to see if assistive devices is enabled\n\ttell application \"System Events\" to set UI_enabled to UI elements enabled\n\tif not UI_enabled then\n\t\ttell application \"AppleScript Utility\"\n\t\t\tactivate\n\t\t\tdisplay dialog \"This script utilizes the built-in Graphical User Interface Scripting architecture of Mac OS X which is currently disabled.\" & return & return & \"You can activate GUI Scripting by selecting the checkbox “Enable GUI Scripting” in AppleScript Utility.\" with icon 1 buttons {\"Okay\"} default button 1\n\t\tend tell\n\tend if\nend UIscript_check\n\nUIscript_check()",
  name: "Check that UI Scripting is Enabled",
  scope: "source.applescript",
  uuid: "E604B44D-3483-4993-9679-566392A03203"},
 {content: 
   "-- \\`menu_click\\`, by Jacob Rus, September 2006\n-- \n-- Accepts a list of form: \\`{\"Finder\", \"View\", \"Arrange By\", \"Date\"}\\`\n-- Execute the specified menu item.  In this case, assuming the Finder \n-- is the active application, arranging the frontmost folder by date.\n\non menu_click(mList)\n\tlocal appName, topMenu, r\n\t\n\t-- Validate our input\n\tif mList's length < 3 then error \"Menu list is not long enough\"\n\t\n\t-- Set these variables for clarity and brevity later on\n\tset {appName, topMenu} to (items 1 through 2 of mList)\n\tset r to (items 3 through (mList's length) of mList)\n\t\n\t-- This overly-long line calls the menu_recurse function with\n\t-- two arguments: r, and a reference to the top-level menu\n\ttell app \"System Events\" to my menu_click_recurse(r, ((process appName)'s (menu bar 1)'s (menu bar item topMenu)'s (menu topMenu)))\nend menu_click\n\non menu_click_recurse(mList, parentObject)\n\tlocal f, r\n\t\n\t-- \\`f\\` = first item, \\`r\\` = rest of items\n\tset f to item 1 of mList\n\tif mList's length > 1 then set r to (items 2 through (mList's length) of mList)\n\t\n\t-- either actually click the menu item, or recurse again\n\ttell app \"System Events\"\n\t\tif mList's length is 1 then\n\t\t\tclick parentObject's menu item f\n\t\telse\n\t\t\tmy menu_click_recurse(r, (parentObject's (menu item f)'s (menu f)))\n\t\tend if\n\tend tell\nend menu_click_recurse",
  name: "Select Menu Item with UI Scripting",
  scope: "source.applescript",
  uuid: "E56CA3CB-D2C0-451F-B695-5E39D152708A"},
 {content: 
   "to split of aString by sep\n\tlocal aList, delims\n\ttell AppleScript\n\t\tset delims to text item delimiters\n\t\tset text item delimiters to sep\n\t\tset aList to text items of aString\n\t\tset  text item delimiters to delims\n\tend tell\n\treturn aList\nend split\n\nto join of aList by sep\n\tlocal aString, delims\n\ttell AppleScript\n\t\tset delims to text item delimiters\n\t\tset text item delimiters to sep\n\t\tset aString to aList as string\n\t\tset text item delimiters to delims\n\tend tell\n\treturn aString\nend join",
  name: "Split/Join Helper Functions",
  scope: "source.applescript",
  uuid: "DB76600C-38FC-4B63-A1B6-CC926496B620"},
 {content: 
   "set oldDelims to AppleScript's text item delimiters\nset AppleScript's text item delimiters to {\"${1:,}\"}\n${0:-- insert actions here}\nset AppleScript's text item delimiters to oldDelims",
  name: "change text item delimiters",
  scope: "source.applescript",
  tabTrigger: "delim",
  uuid: "016BF4B7-53D3-49E0-A8DB-033917FAD031"},
 {content: 
   "considering ${1:case}\n\t${0:-- insert actions here}\nend considering",
  name: "considering … end considering",
  scope: "source.applescript",
  tabTrigger: "con",
  uuid: "F6401A3A-7BDB-41E0-8628-3C2F24C3D5FC"},
 {content: 
   "ignoring ${1:application responses}\n\t${0:-- insert actions here}\nend ignoring",
  name: "ignoring … end ignoring",
  scope: "source.applescript",
  tabTrigger: "ign",
  uuid: "AFC90003-4B8B-4661-8958-81F47D5E8277"},
 {content: "prop parent : app \"${1:TextMate}\"",
  name: "prop parent …",
  scope: "source.applescript",
  tabTrigger: "parent",
  uuid: "26A11710-54A2-4AB1-AE52-213869C21314"},
 {content: "repeat while ${1:condition}\n\t$0\nend repeat",
  name: "repeat while ...",
  scope: "source.applescript",
  tabTrigger: "rep",
  uuid: "82EE8D3B-B2EE-457C-8412-F098DD5827FA"},
 {content: "repeat with $1 in $2\n\t$0\nend repeat",
  name: "repeat with ... in ...",
  scope: "source.applescript",
  tabTrigger: "rep",
  uuid: "1E31B99C-B436-4BA6-A754-E8EE5A73680D"},
 {content: 
   "script ${1:new_object}\n\ton run\n\t\t${0:-- do something interesting}\n\tend run\nend script",
  name: "script … end",
  scope: "source.applescript",
  tabTrigger: "script",
  uuid: "27E30615-B821-4998-AC39-B503B75699DB"}]
