# Encoding: UTF-8

[{content: "\"& ${2:`echo $TM_SELECTED_TEXT`} &\"",
  keyEquivalent: "@\"",
  name: "\"&  &\"",
  scope: "source.asp string.quoted.double",
  uuid: "75A09C24-D28A-4B56-9DCB-5125D9E4555B"},
 {content: 
   "<%# DataBinder.Eval(Container.DataItem, \"${1:${TM_SELECTED_TEXT:ColumnName}}\"${2:, \"{0:C\\}\"}) %>$0",
  keyEquivalent: "^#",
  name: "# Container.DataItem",
  scope: "text.html.asp.net",
  tabTrigger: "#",
  uuid: "DFF5EEC2-48AA-41AE-A0F5-AD0CCC49F285"},
 {content: "\"& Chr(39) &\"",
  keyEquivalent: "'",
  name: "' = \"&Chr(39)&\"",
  scope: 
   "text.html.asp meta.tag string.quoted.single source.asp string.quoted.double, text.html.asp meta.tag.html string.quoted.single.html meta.source.embedded.bound source.asp.embedded.html string.quoted.double.asp, text.html.asp meta.tag string.quoted.single source string.quoted.double",
  uuid: "A0D228AD-2CDA-423A-A621-597238AD472A"},
 {content: "<%= $0 %>",
  name: "<%= %>",
  scope: "text.html.asp",
  tabTrigger: "=",
  uuid: "893BC5DA-1633-48B3-9401-8184F5ABE662"},
 {content: "<%${2:=} ${1:${TM_SELECTED_TEXT:Content}}$0 %>",
  keyEquivalent: "^%",
  name: "<%>",
  scope: "text.html.asp",
  tabTrigger: "p",
  uuid: "F3C06C1F-E04A-42B2-B611-99C48E1F6FC1"},
 {content: 
   "Function ${1:Process}(${2:This_Item} As ${3:String}) As ${4:Boolean}\n\tReturn ${5:True}$0\nEnd Function\n",
  keyEquivalent: "^~",
  name: "Function",
  scope: "source.asp",
  tabTrigger: "function",
  uuid: "312FE06B-D9DA-4EBF-AF43-5CF67CC8A127"},
 {content: 
   "${3:IIf(Request.Querystring(\"s\")<>\"\",Regex.Replace(${1:${TM_SELECTED_TEXT:\"Hello World!!!1!\"}}, \"(\"& Request.Querystring(\"s\") &\")\", \"<${2:span} class='ss'>\\$1</${2:span}>\"),$1)}",
  keyEquivalent: "^~",
  name: "Hilight Search Terms(TEXT)",
  scope: "source.asp",
  tabTrigger: "format",
  uuid: "4BC9912E-93CF-4C5D-A264-425D0151C542"},
 {content: 
   "IIf(${1:${TM_SELECTED_TEXT:Is_This_True?}},${2:true},${3:false})$0",
  keyEquivalent: "^@i",
  name: "IIf()",
  scope: 
   "source.asp -(source string), text string source.asp -(source string)",
  tabTrigger: "IIf",
  uuid: "7624FE5A-4293-4081-BDA8-7CD6534D7D5A"},
 {content: 
   "\"& IIf(${2:Is_This_True?},\"${1:${TM_SELECTED_TEXT:True}}\",${4:\"$3\"})$0 &\"",
  keyEquivalent: "^@i",
  name: "IIf() \"\"",
  scope: "source.asp string",
  tabTrigger: "IIf",
  uuid: "516A2F6B-E1BD-4E30-9CBA-FCB2D400C60B"},
 {content: 
   "<%= IIf(${2:Is_This_True?},\"${1:${TM_SELECTED_TEXT:True}}\",${4:\"$3\"})$0 %>",
  keyEquivalent: "^@i",
  name: "IIf() \"\" html",
  scope: "text.html.asp string -source",
  tabTrigger: "IIf",
  uuid: "FBDCCC35-1DB9-42BE-8C97-96183C2D0CA0"},
 {content: 
   "<% if ${2:Is_This_True?} %>${1:${TM_SELECTED_TEXT:True}}${4:<% else %>$3}<% end if %>$0",
  keyEquivalent: "^@i",
  name: "If then HTML",
  scope: "text.html.asp",
  tabTrigger: "IIf",
  uuid: "E2DA60E2-97F4-42AC-AF9E-5A0C7DE4B724"},
 {content: 
   "${9:<div id=\"search_${1:Orders}\">\n  <form action=\"\" method=\"get\">\n    Search <input name=\"s\" value=\"<%= Request.Querystring(\"s\") %>\" />\n    <input type=\"submit\" value=\"Search ${1:Orders}\" />\n  </form>\n</div>\n}<div id=\"${1:Orders}\">\n${7:\t<%@ Register TagPrefix=\"MM\" Namespace=\"DreamweaverCtrls\" Assembly=\"DreamweaverCtrls,version=1.0.0.0,publicKeyToken=836f606ede05d46a,culture=neutral\" %>\n\t<mm:pagebind runat=\"server\" PostBackBind=\"true\" />\n}\t<mm:dataset ID=\"${1:Orders}\"\n\t runat=\"Server\"\n\t IsStoredProcedure=\"false\"\n\t ConnectionString='<%# System.Configuration.ConfigurationSettings.AppSettings(\"MM_CONNECTION_STRING_${3:Common_LIVE}\") %>'\n\t DatabaseType='<%# System.Configuration.ConfigurationSettings.AppSettings(\"MM_CONNECTION_DATABASETYPE_${3:Common_LIVE}\") %>'\n\t CommandText='<%# \"${2:select * from users where clue is not null}    ORDER BY \"+ IIf((Not Request.Querystring(\"sortOn\") Is Nothing), Request.Querystring(\"sortOn\"), \"${4:username}\") +\" \"+ Request.Querystring(\"sortDir\") %>'\n\t Debug=\"true\" PageSize=\"25\"\n\t >\n\t\t<parameters>${5:\n\t\t\t<parameter  name=\"@s\"  value='<%# \"%\" + IIf((Not Request.Querystring(\"s\") Is Nothing), Request.Querystring(\"s\"), \"\") + \"%\" %>'  type=\"VarChar\"   />\n\t\t}</parameters>${6:\n\t\t<editops>\n\t\t\t<editopstable name=\"dbo.tblFedExSecurity\" />\n\t\t\t<parameter name=\"password\"          type=\"NVarChar\" />\n\t\t\t<parameter name=\"customerid\"        type=\"NVarChar\" />\n\t\t\t<parameter name=\"locationid\"        type=\"Int\"      />\n\t\t\t<parameter name=\"style\"             type=\"NVarChar\" />\n\t\t\t<parameter name=\"sub_style\"         type=\"SmallInt\" />\n\t\t\t<parameter name=\"make_style\"        type=\"SmallInt\" />\n\t\t\t<parameter name=\"shipping_method\"   type=\"SmallInt\" />\n\t\t\t<parameter name=\"type\"              type=\"NVarChar\" />\n\t\t\t<parameter name=\"role\"              type=\"NVarChar\" />\n\t\t\t<parameter name=\"phone\"             type=\"NVarChar\" />\n\t\t\t<parameter name=\"email\"             type=\"VarChar\"  />\n\t\t\t<parameter name=\"viewreport\"        type=\"Bit\"      />\n\t\t\t<parameter name=\"viewreportnumbers\" type=\"Bit\"      />\n\t\t\t<parameter name=\"viewreportmoney\"   type=\"Bit\"      />\n\t\t\t<parameter name=\"viewtracking\"      type=\"Bit\"      />\n\t\t\t<parameter name=\"addlocations\"      type=\"Bit\"      />\n\t\t\t<parameter name=\"viewlocations\"     type=\"Bit\"      />\n\t\t\t<parameter name=\"sendemail\"         type=\"Bit\"      />\n\t\t\t<parameter name=\"fundsallocation\"   type=\"Bit\"      />\n\t\t\t<parameter name=\"supplyordering\"    type=\"Bit\"      />\n\t\t\t<parameter name=\"generatecalltag\"   type=\"Bit\"      />\n\t\t\t<parameter name=\"generateprp\"       type=\"Bit\"      />\n\t\t\t<parameter name=\"viewlogins\"        type=\"Bit\"      />\n\t\t\t<parameter name=\"createlogins\"      type=\"Bit\"      />\n\t\t\t<parameter name=\"${4:username}\" type=\"NVarChar\" isprimary=\"true\" />\n\t\t</editops>}\n\t</mm:dataset>\n\t<script runat=\"server\">\n\tSub ${1:Orders}_sortCommand(sender as Object, e as DataGridSortCommandEventArgs)\n\t\tdim sortDir as string = \"\"\n\t\tif Request.QueryString(\"sortOn\") = e.SortExpression then\n\t\t\tif (Request.QueryString(\"sortDir\") = \"\")\n\t\t\t\tsortDir = \"ASC\"\n\t\t\telse if (Request.QueryString(\"sortDir\") = \"ASC\")\n\t\t\t\tsortDir = \"DESC\"\n\t\t\telse if (Request.QueryString(\"sortDir\") = \"DESC\")\n\t\t\t\tsortDir = \"ASC\"\n\t\t\tend if\n\t\telse\n\t\t\tsortDir = \"ASC\"\n\t\tend if\n\t\tResponse.Redirect(Request.ServerVariables(\"SCRIPT_NAME\") + \"?sortOn=\" + e.SortExpression + \"&sortDir=\" + sortDir + \"&s=\" + Request.Querystring(\"s\"))\n\tend sub\n\t</script>\n\t<asp:DataGrid ID=\"${1:Orders}_DG\"\n\t\t\t\tDataKeyField=\"${4:username}\"\n\t\t\t\tAutoGenerateColumns=\"true\"\n\t\t\t\n\t\t\t\trunat=\"server\"\n\t\t\t\tAllowSorting=\"true\"\n\t\t\t\tOnSortCommand=\"${1:Orders}_sortCommand\"\n\t\t\t\n\t\t\t\tDataSource=\"<%# ${1:Orders}.DefaultView %>\"\n\t\t\t\tOnItemDataBound=\"${1:Orders}.OnDataGridItemDataBound\"\n\t\t\t\tOnEditCommand=\"${1:Orders}.OnDataGridEdit\"\n\t\t\t\tOnUpdateCommand=\"${1:Orders}.OnDataGridUpdate\"\n\t\t\t\tOnDeleteCommand=\"${1:Orders}.OnDataGridDelete\"\n\t\t\t\tOnCancelCommand=\"${1:Orders}.OnDataGridCancel\"\n\t\t\t\n\t\t\t\tAllowPaging=\"true\"\n\t\t\t\tAllowCustomPaging=\"true\"\n\t\t\t\tPageSize=\"<%# ${1:Orders}.PageSize %>\"\n\t\t\t\tOnPageIndexChanged=\"${1:Orders}.OnDataGridPageIndexChanged\"\n\t\t\t\tvirtualitemcount=\"<%# ${1:Orders}.RecordCount %>\"\n\t\t\t\tPagerStyle-Mode=\"NumericPages\"\n\t\t\t\n\t\t\t\tShowHeader=\"true\"\n\t\t\t\tShowFooter=\"false\"\n\t\t>\n\t\t<headerstyle           CssClass=\"headerstyle\"          />\n\t\t<itemstyle             CssClass=\"itemstyle\"            />\n\t\t<alternatingitemstyle  CssClass=\"alternatingitemstyle\" />\n\t\t<footerstyle           CssClass=\"footerstyle\"          />\n\t\t<pagerstyle            CssClass=\"pagerstyle\"           />\n\t\t<columns>\n\t\t\t<asp:EditCommandColumn  ButtonType=\"LinkButton\"  CancelText=\"Cancel\"  EditText=\"Edit\"  HeaderText=\"Edit\"  UpdateText=\"Update\"  visible=\"True\"/>\n\t\t\t$0\n\t\t</columns>\n\t</asp:DataGrid>\n</div>\n",
  keyEquivalent: "^~",
  name: "MM:DataGrid Sort Page Edit",
  scope: "text.html.asp",
  tabTrigger: "datagrid",
  uuid: "68A09D9A-8324-4CCC-AC4A-6D175536EF38"},
 {content: 
   "${9:<div id=\"search_${1:Orders}\">\n  <form action=\"\" method=\"get\">\n    Search <input name=\"s\" value=\"<%= Request.Querystring(\"s\") %>\" />\n    <input type=\"submit\" value=\"Search ${1:Orders}\" />\n  </form>\n</div>\n}<div id=\"${1:Orders}\">\n${7:\t<%@ Register TagPrefix=\"MM\" Namespace=\"DreamweaverCtrls\" Assembly=\"DreamweaverCtrls,version=1.0.0.0,publicKeyToken=836f606ede05d46a,culture=neutral\" %>\n\t<mm:pagebind runat=\"server\" PostBackBind=\"true\" />\n}\t<mm:dataset ID=\"${1:Orders}\"\n\t runat=\"Server\"\n\t IsStoredProcedure=\"false\"\n\t ConnectionString='<%# System.Configuration.ConfigurationSettings.AppSettings(\"MM_CONNECTION_STRING_${3:Common_LIVE}\") %>'\n\t DatabaseType='<%# System.Configuration.ConfigurationSettings.AppSettings(\"MM_CONNECTION_DATABASETYPE_${3:Common_LIVE}\") %>'\n\t CommandText='<%# \"${2:select * from users where clue is not null}    ORDER BY \"+ IIf((Not Request.Querystring(\"sortOn\") Is Nothing), Request.Querystring(\"sortOn\"), \"${4:username}\") +\" \"+ Request.Querystring(\"sortDir\") %>'\n\t Debug=\"true\" PageSize=\"25\"\n\t >\n\t\t<parameters>${5:\n\t\t\t<parameter  name=\"@s\"  value='<%# \"%\" + IIf((Not Request.Querystring(\"s\") Is Nothing), Request.Querystring(\"s\"), \"\") + \"%\" %>'  type=\"VarChar\"   />\n\t\t}</parameters>\n\t</mm:dataset>\n\t<script runat=\"server\">\n\tSub ${1:Orders}_sortCommand(sender as Object, e as DataGridSortCommandEventArgs)\n\t\tdim sortDir as string = \"\"\n\t\tif Request.QueryString(\"sortOn\") = e.SortExpression then\n\t\t\tif (Request.QueryString(\"sortDir\") = \"\")\n\t\t\t\tsortDir = \"ASC\"\n\t\t\telse if (Request.QueryString(\"sortDir\") = \"ASC\")\n\t\t\t\tsortDir = \"DESC\"\n\t\t\telse if (Request.QueryString(\"sortDir\") = \"DESC\")\n\t\t\t\tsortDir = \"ASC\"\n\t\t\tend if\n\t\telse\n\t\t\tsortDir = \"ASC\"\n\t\tend if\n\t\tResponse.Redirect(Request.ServerVariables(\"SCRIPT_NAME\") + \"?sortOn=\" + e.SortExpression + \"&sortDir=\" + sortDir + \"&s=\" + Request.Querystring(\"s\"))\n\tend sub\n\t</script>\n\t<asp:DataGrid ID=\"${1:Orders}_DG\"\n\t\t\t\tDataKeyField=\"${4:username}\"\n\t\t\t\tAutoGenerateColumns=\"true\"\n\t\t\t\t\n\t\t\t\trunat=\"server\"\n\t\t\t\tAllowSorting=\"true\"\n\t\t\t\tOnSortCommand=\"${1:Orders}_sortCommand\"\n\t\t\t\t\n\t\t\t\tDataSource=\"<%# ${1:Orders}.DefaultView %>\"\n\t\t\t\tOnItemDataBound=\"${1:Orders}.OnDataGridItemDataBound\"\n\t\t\t\t\n\t\t\t\tAllowPaging=\"true\"\n\t\t\t\tAllowCustomPaging=\"true\"\n\t\t\t\tPageSize=\"<%# ${1:Orders}.PageSize %>\"\n\t\t\t\tOnPageIndexChanged=\"${1:Orders}.OnDataGridPageIndexChanged\"\n\t\t\t\tvirtualitemcount=\"<%# ${1:Orders}.RecordCount %>\"\n\t\t\t\tPagerStyle-Mode=\"NumericPages\"\n\t\t\t\tPagerStyle-Position=\"${10:Bottom|Top|TopAndBottom}\"\n\t\t\t\t\n\t\t\t\tShowHeader=\"true\"\n\t\t\t\tShowFooter=\"false\"\n\t\t\t\tEnableViewstate=\"false\"\n\t\t>\n\t\t<headerstyle           CssClass=\"headerstyle\"          />\n\t\t<itemstyle             CssClass=\"itemstyle\"            />\n\t\t<alternatingitemstyle  CssClass=\"alternatingitemstyle\" />\n\t\t<footerstyle           CssClass=\"footerstyle\"          />\n\t\t<pagerstyle            CssClass=\"pagerstyle\"           />\n\t\t<columns>\n\t\t\t$0\n\t\t</columns>\n\t</asp:DataGrid>\n</div>\n",
  keyEquivalent: "^~",
  name: "MM:DataGrid Sort Page Search",
  scope: "text.html.asp",
  tabTrigger: "datagrid",
  uuid: "0DAEDF6F-7009-4CBC-B175-3146F02903ED"},
 {content: 
   "${10:Regex.Replace(${1:${TM_SELECTED_TEXT:\"Hello World!!!!1!\"}}$0,\"${3:[^_\\w\\d\\s]}\",\"$4\")}",
  keyEquivalent: "^~",
  name: "Regex.Replace()",
  scope: "source.asp",
  tabTrigger: "write",
  uuid: "5541855F-D39A-48BB-AC67-E946C3EFB467"},
 {content: "${2:Request.Cookies}(\"${1:${TM_SELECTED_TEXT:VariableName}}\")$0",
  keyEquivalent: "@(",
  name: "Request.Cookies (ASP)",
  scope: "source.asp, text.html.asp",
  uuid: "699E82AF-02FA-43C3-9B31-EAB7D65F6099"},
 {content: "${2:Request.Form}(\"${1:${TM_SELECTED_TEXT:VariableName}}\")$0",
  keyEquivalent: "@(",
  name: "Request.Form (ASP)",
  scope: "source.asp, text.html.asp",
  uuid: "18158109-9DF4-4070-9533-A5C414448C99"},
 {content: 
   "${2:Request.QueryString}(\"${1:${TM_SELECTED_TEXT:VariableName}}\")$0",
  keyEquivalent: "@(",
  name: "Request.QueryString (ASP)",
  scope: "source.asp, text.html.asp",
  uuid: "B535C3C8-D1B5-44FA-A7A4-22A53E51021F"},
 {content: 
   "${3:Response.Write(${1:${TM_SELECTED_TEXT:\"Hello World!!!!1!\"}})}",
  keyEquivalent: "^~",
  name: "Response.Write()",
  scope: "source.asp",
  tabTrigger: "write",
  uuid: "FBE6DBA4-ADBA-4744-971E-1E61E6FD5992"},
 {content: 
   "Dim conn$1 as New SqlConnection(ConfigurationSettings.AppSettings(\"${4:MM_CONNECTION_STRING_TIW_LIVE}\"))'1. Create a connection\nConst strSQL$1 as String = \"${2:SELECT * FROM Users WHERE Clue > 0}\"'2. Create the command object, passing in the SQL string\nDim comm$1 as New SqlCommand(strSQL$1, conn$1)\nconn$1.Open()\n  ${1:${TM_SELECTED_TEXT:IdOfThinggy}}.DataSource = comm$1.ExecuteReader(CommandBehavior.CloseConnection)\n  ${1:${TM_SELECTED_TEXT:IdOfThinggy}}.DataBind()'Set the datagrid's datasource to the datareader and databind \nconn$1.Close()$0",
  keyEquivalent: "^~",
  name: "SQLDataReader Bound",
  scope: "source.asp",
  tabTrigger: "sql",
  uuid: "AF62ECDD-219A-44A8-B47F-7B1F538DC241"},
 {content: 
   "Dim con$4 as new System.Data.SQLClient.SQLConnection(System.Configuration.ConfigurationSettings.AppSettings(\"${3:MM_CONNECTION_STRING_TIW_LIVE}\")) \ncon$4.Open()\n\tDim strSQL$4 as String = \"${1:${TM_SELECTED_TEXT:SELECT * FROM Users WHERE Clue > 0}}\"\n\tDim    com$4 as new System.Data.SQLClient.SQLCommand(strSQL$4, Con$4)\n\tDim      r$4 as System.Data.SQLClient.SQLDataReader = Com$4.ExecuteReader()\n\tWhile    r$4.Read()\n\t\t${5:r$4(0)}$0\n\tEnd While\n\tr$4.Close()\ncon$4.close()\n",
  keyEquivalent: "^~",
  name: "SQLDataReader Loop",
  scope: "source.asp",
  tabTrigger: "sql",
  uuid: "A20AA1B8-4F3E-492B-B619-2EF46832CB69"},
 {content: 
   "<TABLE>\n  <TR>\n    <TD>\n      <B>Server Varriable</B>\n    </TD>\n    <TD>\n      <B>Value</B>\n    </TD>\n  </TR>\n  <% dim name as string %>\n  <% For Each name In Request.ServerVariables %>\n  <TR>\n    <TD>\n      <%= name %>\n    </TD>\n    <TD>\n      <%= Request.ServerVariables(name) %>\n    </TD>\n  </TR>\n  <% Next %>\n</TABLE>\n",
  keyEquivalent: "^~",
  name: "ServerVariables",
  scope: "text.html.asp.net",
  uuid: "D24D1AAC-F745-4120-A9A3-85C22083A927"},
 {content: "${2:Session}(\"${1:${TM_SELECTED_TEXT:VariableName}}\")$0",
  keyEquivalent: "@(",
  name: "Session (ASP)",
  scope: "source.asp, text.html.asp",
  uuid: "7598D75F-6649-4BDF-9FC4-6E8782C66B66"},
 {content: 
   "Dim $4_CON As New System.Data.SQLClient.SQLConnection(System.Configuration.ConfigurationSettings.AppSettings(\"MM_CONNECTION_STRING_${2:CFC_LIVE}\"))\nDim $4_COM As New System.Data.SQLClient.SqlCommand( \"${1:${TM_SELECTED_TEXT:UPDATE Users SET Clue = 1 WHERE username = 'taylott'}}\", $4_CON)\n$4_COM.Connection.Open()\n$4_COM.ExecuteNonQuery()\n$4_COM.Connection.Close()\n",
  keyEquivalent: "^~",
  name: "SqlCommand",
  scope: "source.asp",
  tabTrigger: "sql",
  uuid: "142C4861-B95A-4DBB-A693-1996AF4A62A5"},
 {content: 
   "${3:String.Format(\"${2:{0:c\\}}\", ${1:${TM_SELECTED_TEXT:price}})}",
  keyEquivalent: "^~",
  name: "String.Format()",
  scope: "source.asp",
  tabTrigger: "format",
  uuid: "14B0D39F-DEF8-435E-82D3-FB992B042A81"},
 {content: 
   "sub ${2:Process}(${2:sender as Object, e as EventArgs})\n\t${1:${TM_SELECTED_TEXT:'Do that thing you do}}$0\nend sub\n",
  name: "Sub",
  scope: "source.asp",
  tabTrigger: "sub",
  uuid: "BD4C231E-8F19-4ACA-844B-B0F4D065D2AD"},
 {content: 
   "\t${1:Process}($2)\n${3:sub ${1:Process}($2)\n${TM_SELECTED_TEXT:'Do that thing you do\n}$0end sub\n}",
  keyEquivalent: "^~",
  name: "Sub (group selection)",
  scope: "source.asp",
  uuid: "56A9D3BB-181D-4950-9389-664E2435DC3C"},
 {content: 
   "<asp:BoundColumn HeaderText=\"${1:${TM_SELECTED_TEXT:ColumnName}}\" DataField=\"${1:${TM_SELECTED_TEXT:ColumnName}}\" SortExpression=\"${1:${TM_SELECTED_TEXT:ColumnName}}\" ${2:ReadOnly=\"True\" ${3:DataFormatString=\"{0:C\\}\" FooterText=\"${1:${TM_SELECTED_TEXT:ColumnName}}\" }}/>",
  keyEquivalent: "^~",
  name: "asp:BoundColumn",
  scope: "text.html.asp.net",
  tabTrigger: "asp:",
  uuid: "9ACAEFB8-C366-41F5-9DD9-61C646C00548"},
 {content: 
   "<asp:TemplateColumn HeaderText=\"${1:${TM_SELECTED_TEXT:ColumnName}}\" ${2:ReadOnly=\"True\" ${3:FooterText=\"${1:${TM_SELECTED_TEXT:ColumnName}}\" }}>\n\t<ItemTemplate>${9:\n\t\t<%# DataBinder.Eval(Container.DataItem, \"${1:${TM_SELECTED_TEXT:ColumnName}}\"${8:, \"{0:C\\}\"}) %>$0\n\t}</ItemTemplate>${10:\n\t<EditItemTemplate>${11:\n\t\t<input name=\"${1:${TM_SELECTED_TEXT:ColumnName}}\" type=\"text\" value=\"<%# DataBinder.Eval(Container.DataItem, \"${1:${TM_SELECTED_TEXT:ColumnName}}\"${8:, \"{0:C\\}\"}) %>\" size=\"\" maxlength=\"\" />\n\t}</EditItemTemplate>}\n</asp:TemplateColumn>",
  keyEquivalent: "^~",
  name: "asp:TemplateColumn",
  scope: "text.html.asp.net",
  tabTrigger: "asp:",
  uuid: "D49E16DC-34E3-480F-903C-6AB0E2408B93"},
 {content: 
   "<asp:TemplateColumn HeaderText=\"${1:`echo $TM_SELECTED_TEXT`}\" Visible=\"True\">\n\t<itemtemplate><asp:CheckBox ID=\"${1:`echo $TM_SELECTED_TEXT`}\" runat=\"server\" Checked='<%# Users.FieldValue(\"${1:`echo $TM_SELECTED_TEXT`}\", Container) %>' enabled=\"false\" /></itemtemplate>\n\t<edititemtemplate>\n\t\t<asp:CheckBox ID=\"${1:`echo $TM_SELECTED_TEXT`}\" runat=\"server\" Checked='<%# Users.FieldValue(\"${1:`echo $TM_SELECTED_TEXT`}\", Container) %>' />\n\t</edititemtemplate>\n</asp:TemplateColumn>\n",
  keyEquivalent: "^~",
  name: "asp:TemplateColumn Checkbox",
  scope: "text.html.asp.net",
  tabTrigger: "asp:",
  uuid: "E740C23F-7520-4685-9165-045CD52DDF21"},
 {content: "\"& vbCr${2:Lf} _\n& \"$1$0",
  keyEquivalent: "#",
  name: "vbCrLf",
  scope: "source.asp string",
  uuid: "971CECA8-CC9E-4E4F-A7EE-92392E6101BF"},
 {content: "StrConv(${1:${TM_SELECTED_TEXT:\"String\"}}, vbProperCase)",
  keyEquivalent: "^~u",
  name: "vbProperCase",
  scope: "source.asp -string",
  uuid: "934D018D-DD49-4024-9E79-BC591EAEE5E0"},
 {content: "StrConv(${1:${TM_SELECTED_TEXT:\"String\"}}, vbUpperCase)",
  keyEquivalent: "^u",
  name: "vbUpperCase",
  scope: "source.asp -string",
  uuid: "549205DD-8595-449C-B4E6-C088045D76AD"}]
