# Encoding: UTF-8

[{content: "**${1:${TM_SELECTED_TEXT}}**",
  keyEquivalent: "@b",
  name: "Bold",
  scope: "text.txt2tags",
  uuid: "96025CA6-A2F9-41A3-8AFF-1DDF88FFECB8"},
 {content: 
   "%%date(year:%Y month:%m day:%d hour:%H min:%M sec:%S date:%c weekday:%A %a month-name:%B %b)",
  name: "Current Date",
  scope: "text.txt2tags",
  tabTrigger: "date",
  uuid: "7568C1CA-5D02-46A0-8395-E3E03CA1D802"},
 {content: 
   "%!encoding(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): ${2:utf-8}\n",
  name: "Encoding",
  scope: "text.txt2tags",
  tabTrigger: "encoding",
  uuid: "F9E37C13-90B1-4E33-80FA-8898DA5AB5D3"},
 {content: 
   "[${1:${TM_SELECTED_TEXT:`#!/usr/bin/env ruby\n\ndef make_link(text)\n  case text\n  when %r{\\A(?i)(.*\\.(png|jpe?g|gif|eps|bmp))\\z}:     \"\#{$1}\"\n  else \"Picture.jpg\"\n  end\nend\n\ntext = %x{__CF_USER_TEXT_ENCODING=$UID:0x8000100:0x8000100 pbpaste}.strip\nprint make_link(text)\n`}}]",
  keyEquivalent: "^I",
  name: "Image",
  scope: "text.txt2tags",
  tabTrigger: "[",
  uuid: "86555501-E5E7-46B7-9DDE-4ABD3C8DF7BB"},
 {content: 
   "%!includeconf(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): ${2:file.t2t}\n",
  name: "Include Config",
  scope: "text.txt2tags",
  tabTrigger: "include",
  uuid: "4FB90B5F-9C32-49BF-951D-6D7CCEB3268D"},
 {content: 
   "%!include(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): \"\"${2:file}\"\"\n",
  name: "Include as Raw",
  scope: "text.txt2tags",
  tabTrigger: "include",
  uuid: "634ABB16-5281-447A-B9A9-062F7E59CB63"},
 {content: 
   "%!include(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): ''${2:file}''\n",
  name: "Include as Tagged",
  scope: "text.txt2tags",
  tabTrigger: "include",
  uuid: "91037021-9141-40D7-AC9D-1C021FBCA0BF"},
 {content: 
   "%!include(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): ${2:file.t2t}\n",
  name: "Include as Txt2tags",
  scope: "text.txt2tags",
  tabTrigger: "include",
  uuid: "AD73EAA2-7972-4B8D-947B-F61790A126E7"},
 {content: 
   "%!include(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): ``${2:file.txt}``\n",
  name: "Include as Verbatim",
  scope: "text.txt2tags",
  tabTrigger: "include",
  uuid: "B486368C-0C1B-4A3A-9E10-D36FF5A2A33D"},
 {content: 
   "%%infile(file:%f extension:%e dir:%d path:%p file-without-extension:%F parent-dir:%D)",
  name: "Input File",
  scope: "text.txt2tags",
  tabTrigger: "infile",
  uuid: "9F9109A4-5AA2-490A-B9D9-62FE8EA25EDD"},
 {content: "//${1:${TM_SELECTED_TEXT}}//",
  keyEquivalent: "@i",
  name: "Italic",
  scope: "text.txt2tags",
  uuid: "4E1C5783-8868-4E8C-83DD-394AFC9A6E93"},
 {content: 
   "[${1:${TM_SELECTED_TEXT:Site Name}} ${2:`#!/usr/bin/env ruby\n\ndef entity_escape(text)\n  # no need to escape, txt2tags already does it\n  return text\nend\n\ndef make_link(text)\n  case text\n  when %r{\\A(mailto:)?(.*?@.*\\..*)\\z}:        \"mailto:\#{$2}\"\n  when %r{\\A[a-zA-Z][a-zA-Z0-9.+-]*://.*\\z}:  entity_escape(text)\n  when %r{\\A.*\\.(com|uk|net|org|info)\\z}:     \"http://\#{entity_escape text}\"\n  when %r{\\A\\S+\\z}:                           entity_escape(text)\n  else                                        \"http://example.com/\"\n  end\nend\n\ntext = %x{__CF_USER_TEXT_ENCODING=$UID:0x8000100:0x8000100 pbpaste}.strip\nprint make_link(text)\n\n`}]",
  keyEquivalent: "^L",
  name: "Link",
  scope: "text.txt2tags",
  tabTrigger: "[",
  uuid: "2C8ED762-B898-4BEE-93C0-4006ED03DFC1"},
 {content: 
   "%%mtime(year:%Y month:%m day:%d hour:%H min:%M sec:%S date:%c weekday:%A %a month-name:%B %b)",
  name: "Modification Time",
  scope: "text.txt2tags",
  tabTrigger: "mtime",
  uuid: "754558C3-8AD5-4CCC-8AF8-3AFE7240D2E5"},
 {content: "\\`\\`${1:${TM_SELECTED_TEXT}}\\`\\`",
  keyEquivalent: "@k",
  name: "Monospaced",
  scope: "text.txt2tags",
  uuid: "BF5F154C-AD22-4191-AF49-4B0ECC850575"},
 {content: "+ ${1:${TM_SELECTED_TEXT:My Title}} +${2:[${3:optional-anchor}]}",
  keyEquivalent: "^+",
  name: "Numbered Title",
  scope: "text.txt2tags",
  tabTrigger: "+",
  uuid: "1295273D-5E3D-454A-A974-81DC71B54A9E"},
 {content: 
   "%!options(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): ${2:--no-headers | --enum-title | --toc | --toc-level n | --css-sugar | --css-inside | --mask-email | --config-file file | --outfile file}\n",
  name: "Options",
  scope: "text.txt2tags",
  tabTrigger: "options",
  uuid: "4C0F88EF-370A-4CBE-9080-A0A44D9D30A9"},
 {content: 
   "%%outfile(file:%f extension:%e dir:%d path:%p file-without-extension:%F parent-dir:%D)",
  name: "Output File",
  scope: "text.txt2tags",
  tabTrigger: "outfile",
  uuid: "4365D25B-0958-457B-80BB-EB2B6868F212"},
 {content: 
   "%!postproc(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): \"${2:pattern}\" \"${3:replacement}\" \n",
  name: "Post-Processing",
  scope: "text.txt2tags",
  tabTrigger: "filter",
  uuid: "141392EF-DDC2-429A-AFD6-8524A2400934"},
 {content: 
   "%!preproc(${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}): \"${2:pattern}\" \"${3:replacement}\" \n",
  name: "Pre-Processing",
  scope: "text.txt2tags",
  tabTrigger: "filter",
  uuid: "F374D5CA-5EA1-4ECA-9AF1-CF3953C0B97E"},
 {content: "\"\"${1:${TM_SELECTED_TEXT}}\"\"",
  name: "Protected (Raw)",
  scope: "text.txt2tags",
  uuid: "29977512-BA22-4686-B833-574316E6E8F3"},
 {content: 
   "\n\"\"\"\n$0${TM_SELECTED_TEXT:- insert raw text here -}\n\"\"\"\n",
  name: "Protected Block (Raw)",
  scope: "text.txt2tags",
  uuid: "F17DB8FF-3314-47EA-B3BC-09B65AD1ED94"},
 {content: "\t${1:- insert quote here -}",
  name: "Quote",
  scope: "text.txt2tags",
  tabTrigger: ">",
  uuid: "EE375C32-C5E7-4D2B-B827-D8C58C79815C"},
 {content: "--${1:${TM_SELECTED_TEXT}}--",
  keyEquivalent: "@\x7F",
  name: "Strike",
  scope: "text.txt2tags",
  uuid: "2ABF61A7-6FF1-4A80-9A34-AEA721DE0C2E"},
 {content: "%!style(${1:html | xhtml | tex}): ${2:style.css}\n",
  name: "Style",
  scope: "text.txt2tags",
  tabTrigger: "style",
  uuid: "D27E6B35-E79C-4D01-84ED-43760577F602"},
 {content: "\n%%toc\n",
  name: "Table Of Contents",
  scope: "text.txt2tags",
  tabTrigger: "toc",
  uuid: "CEB79704-3ADE-41AE-9AD4-9C31023F41D5"},
 {content: 
   "%!target: ${1:html | xhtml | sgml | tex | lout | man | mgp | wiki | gwiki | doku | moin | pm6 | txt}\n",
  name: "Target",
  scope: "text.txt2tags",
  tabTrigger: "target",
  uuid: "984D6F16-CDC4-4AB7-AB34-F0C6094D517E"},
 {content: "= ${1:${TM_SELECTED_TEXT:My Title}} =${2:[${3:optional-anchor}]}",
  keyEquivalent: "^=",
  name: "Title",
  scope: "text.txt2tags",
  tabTrigger: "=",
  uuid: "540AA439-3D16-4CB7-97AA-F6CAA1AAE87E"},
 {content: "__${1:${TM_SELECTED_TEXT}}__",
  keyEquivalent: "@u",
  name: "Underline",
  scope: "text.txt2tags",
  uuid: "7E89AE2D-2C71-4739-B95E-47D2697C690D"},
 {content: 
   "\n\\`\\`\\`\n${1:${TM_SELECTED_TEXT:- insert code here -}}\n\\`\\`\\`\n",
  keyEquivalent: "~@k",
  name: "Verbatim Block (Code)",
  scope: "text.txt2tags",
  tabTrigger: "`",
  uuid: "B78FDA0E-AC0A-467E-91A3-FD8923F4DA62"}]
